"""
FrontendStack - Static frontend hosting for Aria (Workshop Module 08).

Creates:
  - S3 bucket (private, no public access)
  - CloudFront distribution with OAC
  - BucketDeployment to upload frontend files
  - Generated config.js with API URL, Cognito settings
  - Custom resource to update Cognito callback URLs with CloudFront URL

Uses the existing Cognito User Pool and Client created by the workshop
CloudFormation template. Cognito IDs are read from CDK context.

Exports:
  - CloudFront distribution URL, bucket name, distribution ID
"""

import os

import aws_cdk as cdk
from aws_cdk import (
    aws_cloudfront as cloudfront,
    aws_cloudfront_origins as origins,
    aws_iam as iam,
    aws_s3 as s3,
    aws_s3_deployment as s3deploy,
    custom_resources as cr,
    CfnOutput,
    Stack,
)
from constructs import Construct


class FrontendStack(Stack):

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        api_url: str,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # ----- Context variables -----
        user_pool_id = self.node.try_get_context("user_pool_id") or "PLACEHOLDER"
        client_id = self.node.try_get_context("client_id") or "PLACEHOLDER"
        cognito_domain = self.node.try_get_context("cognito_domain") or "PLACEHOLDER"
        runtime_id = self.node.try_get_context("runtime_id") or "PLACEHOLDER"
        account_id = self.node.try_get_context("account_id") or self.account

        # ----- S3 Bucket -----
        bucket = s3.Bucket(
            self,
            "AriaFrontendBucket",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            removal_policy=cdk.RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        # ----- CloudFront Distribution -----
        distribution = cloudfront.Distribution(
            self,
            "AriaDistribution",
            comment="Aria AI assistant frontend",
            default_behavior=cloudfront.BehaviorOptions(
                origin=origins.S3BucketOrigin.with_origin_access_control(bucket),
                viewer_protocol_policy=cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                cache_policy=cloudfront.CachePolicy.CACHING_OPTIMIZED,
                allowed_methods=cloudfront.AllowedMethods.ALLOW_GET_HEAD,
                compress=True,
            ),
            default_root_object="index.html",
            error_responses=[
                cloudfront.ErrorResponse(
                    http_status=404,
                    response_http_status=200,
                    response_page_path="/index.html",
                    ttl=cdk.Duration.seconds(0),
                ),
                cloudfront.ErrorResponse(
                    http_status=403,
                    response_http_status=200,
                    response_page_path="/index.html",
                    ttl=cdk.Duration.seconds(0),
                ),
            ],
            price_class=cloudfront.PriceClass.PRICE_CLASS_100,
            minimum_protocol_version=cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
        )

        # ----- Generate config.js -----
        cloudfront_url = f"https://{distribution.distribution_domain_name}"
        cognito_domain_url = (
            f"https://{cognito_domain}.auth.{self.region}.amazoncognito.com"
        )

        runtime_url = (
            f"https://bedrock-agentcore.{self.region}.amazonaws.com"
            f"/runtimes/{runtime_id}/invocations"
            f"?qualifier=DEFAULT&accountId={account_id}"
        )

        config_js_content = f"""\
// Auto-generated by CDK at deploy time. Do not edit manually.
window.ARIA_CONFIG = {{
    API_URL: "{api_url}",
    RUNTIME_URL: "{runtime_url}",
    COGNITO_DOMAIN: "{cognito_domain_url}",
    USER_POOL_ID: "{user_pool_id}",
    CLIENT_ID: "{client_id}",
    REDIRECT_URI: "{cloudfront_url}/callback",
    LOGOUT_URI: "{cloudfront_url}/",
    REGION: "{self.region}"
}};
"""

        # ----- Deploy frontend files to S3 -----
        frontend_path = os.path.join(
            os.path.dirname(__file__), "..", "..", "frontend"
        )

        frontend_deploy = s3deploy.BucketDeployment(
            self,
            "DeployFrontend",
            sources=[s3deploy.Source.asset(frontend_path)],
            destination_bucket=bucket,
            distribution=distribution,
            distribution_paths=["/*"],
        )

        config_deploy = s3deploy.BucketDeployment(
            self,
            "DeployConfig",
            sources=[s3deploy.Source.data("config.js", config_js_content)],
            destination_bucket=bucket,
            distribution=distribution,
            distribution_paths=["/config.js"],
            prune=False,
        )
        config_deploy.node.add_dependency(frontend_deploy)

        # ----- Update Cognito callback URLs with CloudFront URL -----
        # Solves the circular dependency: the workshop CFN template can't know
        # the CloudFront URL at creation time.
        user_pool_arn = (
            f"arn:aws:cognito-idp:{self.region}:{self.account}:{user_pool_id}"
        )

        cr.AwsCustomResource(
            self,
            "UpdateCognitoCallbackUrls",
            on_create=cr.AwsSdkCall(
                service="CognitoIdentityServiceProvider",
                action="updateUserPoolClient",
                parameters={
                    "UserPoolId": user_pool_id,
                    "ClientId": client_id,
                    "ExplicitAuthFlows": [
                        "ALLOW_USER_SRP_AUTH",
                        "ALLOW_USER_PASSWORD_AUTH",
                        "ALLOW_REFRESH_TOKEN_AUTH",
                    ],
                    "AllowedOAuthFlows": ["code"],
                    "AllowedOAuthFlowsUserPoolClient": True,
                    "AllowedOAuthScopes": ["openid", "email", "profile"],
                    "SupportedIdentityProviders": ["COGNITO"],
                    "CallbackURLs": [
                        "http://localhost:3000/",
                        "http://localhost:3000/callback",
                        f"{cloudfront_url}/",
                        f"{cloudfront_url}/callback",
                    ],
                    "LogoutURLs": [
                        "http://localhost:3000/",
                        f"{cloudfront_url}/",
                    ],
                },
                physical_resource_id=cr.PhysicalResourceId.of(
                    f"cognito-callback-{client_id}"
                ),
            ),
            on_update=cr.AwsSdkCall(
                service="CognitoIdentityServiceProvider",
                action="updateUserPoolClient",
                parameters={
                    "UserPoolId": user_pool_id,
                    "ClientId": client_id,
                    "ExplicitAuthFlows": [
                        "ALLOW_USER_SRP_AUTH",
                        "ALLOW_USER_PASSWORD_AUTH",
                        "ALLOW_REFRESH_TOKEN_AUTH",
                    ],
                    "AllowedOAuthFlows": ["code"],
                    "AllowedOAuthFlowsUserPoolClient": True,
                    "AllowedOAuthScopes": ["openid", "email", "profile"],
                    "SupportedIdentityProviders": ["COGNITO"],
                    "CallbackURLs": [
                        "http://localhost:3000/",
                        "http://localhost:3000/callback",
                        f"{cloudfront_url}/",
                        f"{cloudfront_url}/callback",
                    ],
                    "LogoutURLs": [
                        "http://localhost:3000/",
                        f"{cloudfront_url}/",
                    ],
                },
                physical_resource_id=cr.PhysicalResourceId.of(
                    f"cognito-callback-{client_id}"
                ),
            ),
            policy=cr.AwsCustomResourcePolicy.from_statements([
                iam.PolicyStatement(
                    actions=["cognito-idp:UpdateUserPoolClient"],
                    resources=["*"],
                ),
            ]),
        )

        # ----- Outputs -----
        CfnOutput(
            self,
            "CloudFrontUrl",
            value=cloudfront_url,
            description="Aria frontend URL",
        )

        CfnOutput(
            self,
            "BucketName",
            value=bucket.bucket_name,
            description="Aria frontend S3 bucket name",
        )

        CfnOutput(
            self,
            "DistributionId",
            value=distribution.distribution_id,
            description="CloudFront distribution ID",
        )
