# Mapping from Jargon Portuguese (currently in the files) to Informal Portuguese

informal_translations = {
  "# Configuração matriz": "# Configuração",
  "# Aplicação Runtime atrelada": "# App do Runtime",
  "# A instância de Agente é puramente orquestrada na primeira invocação atada e persistida unificada para subsequentes": "# O Agente é criado na primeira vez que é chamado e reutilizado nas próximas",
  "# iterações orgânicas na mesma malha de sessão. O Runtime providencia que cada": "# chamadas da mesma sessão. O Runtime garante que cada",
  "# sessão AWS opere blindada estrita em sua microVM isolada unificada, mantendo apenas um fluxo de matriz aqui.": "# sessão rode isolada na sua própria microVM, então só existe uma sessão rodando aqui.",
  "# Instanciado iterativo no primeiro gatilho, reaproveitado pelo ciclo orgânico base de vida da microVM AWS.": "# Criado na primeira execução, e reaproveitado enquanto a microVM estiver viva.",
  "# O ecossistema Runtime blinda uma sessão unificada por microVM, dispensando gestão orgânica de multi-sessions.": "# O Runtime garante uma sessão por microVM, então não precisamos nos preocupar com gestão de múltiplas sessões.",
  "# --- Tools (Ferramentas Nativas) ---------------------------------------------------------------": "# --- Tools (Ferramentas) ---------------------------------------------------------------",
  "# --- Memory (Memória Atada) --------------------------------------------------------------": "# --- Memory (Memória) --------------------------------------------------------------",
  "# --- Agent (Instância Matriz) ---------------------------------------------------------------": "# --- Agent (Agente) ---------------------------------------------------------------",
  "# Orquestra as importações nativas AWS do diretório shared/": "# Permite importar arquivos da pasta shared/",
  "# Inspeciona interativo a nuvem para verificar ocorrência nativa AWS": "# Verifica se o recurso já existe na AWS",
  "# Orquestra e provisiona novo bucket de Memory unificado na AWS": "# Cria uma nova memória para o agente",
  "# Mantém polling da nuvem atado aguardando status ACTIVE orgânico provado": "# Aguarda até que o status fique como ACTIVE",
  "# --- Cliente MCP de matriz Gateway atado --------------------------------------------------": "# --- Cliente MCP do Gateway --------------------------------------------------",
  "# Extração puramente unificada de outputs do CFN": "# Descobre automaticamente usando as saídas do CloudFormation",
  "# --- Passo 1: Orquestrar e Implantar a Matriz Gateway ---": "# --- Passo 1: Criar o Gateway ---",
  "# Analisar infraestrutura atada orgânica existente": "# Verifica se já existe um gateway criado",
  "# Interligado paralelo aguardando o status READY unificado": "# Aguarda até ficar com status READY",
  "# --- Passo 2: Embutir Target de matriz orgânico ---": "# --- Passo 2: Adicionar um Target ---",
  "# Extrai a configuração estruturada do gateway base": "# Carrega as configurações salvas do gateway",
  "# --- Passo 1: Instanciar Motor de Cedar Policy ---": "# --- Passo 1: Criar o Policy Engine (Motor de Políticas) ---",
  "# --- Passo 2: Empacotar Políticas restritas Cedar ---": "# --- Passo 2: Criar as Políticas Cedar ---",
  "# Delay isolado atado para propagação e espalhamento das policies AWS": "# Dá um tempinho para as políticas se propagarem na rede",
  "# --- Passo 3: Interligar blindagem ao Gateway puro ---": "# --- Passo 3: Conectar a política ao Gateway ---",
  "# Consolida arquivo remoto atado unificado AWS config": "# Salva as configurações",
  "# Arquiva também matriz unificada atada referencial dos arquivos Cedar provados": "# Também salva os arquivos Cedar separadamente para referência",
  "# --- Fase 1: Emular instâncias avaliadoras base orgânicas ---": "# --- Fase 1: Criar os avaliadores ---",
  "# --- Fase 2: Configuração liminar puramente matriz online de avaliação ---": "# --- Fase 2: Configurações de avaliação online ---",
  "# Aponta o index AWS CloudWatch para traces do ecossistema AgentCore Runtime": "# Pega o grupo de logs do CloudWatch onde ficam os traces do AgentCore Runtime",
  "# Resgata a matriz de histórico de eventos iterativos desta malha.": "# Pega o histórico de eventos da conversa para essa sessão.",
  "# Indexa os vetores nativos por timestamp orgânico (cronologia reversa unificada AWS)": "# Ordena os eventos por data e hora (os mais antigos primeiro para manter a ordem da conversa)",
  "# Trata iterativo os vetores forjando um array limpo de histórico atado": "# Limpa e formata os eventos em um formato mais fácil de ler",
  "# Pula chamadas brutas (tool/result) — exibe subjacente puramente a carga orgânica estruturada humana": "# Ignora mensagens técnicas de ferramentas — mostra apenas o texto real da conversa",
  "# ----- Variáveis de Matriz Contextual (injetadas via deploy_frontend.py) -----": "# ----- Variáveis de contexto (preenchidas pelo deploy_frontend.py) -----",
  "# AWS Endpoint nativo /invocations puro (orquestra suporte JWT restrito + streaming)": "# Endpoint /invocations do AgentCore Runtime (suporta JWT + streaming)",
  "# ----- Varredura da nuvem em busca de Cognito User Pool atrelado -----": "# ----- Busca o Cognito User Pool existente -----",
  "# ----- Roteador REST API puro -----": "# ----- REST API -----",
  "# ----- Configuração estrita de CORS -----": "# ----- Configurações de CORS -----",
  "# ----- Orquestrador de Identidade Cognito -----": "# ----- Autorizador do Cognito -----",
  "# ----- Role AWS IAM de matriz puramente atrelada para o API Gateway acionar o Runtime -----": "# ----- Role do IAM para o API Gateway conseguir chamar o Runtime -----",
  "# POST /chat -- Proxy de fluxo unificado de rede paralelo para a matriz AgentCore": "# POST /chat -- Rota que repassa a chamada via streaming para o AgentCore Runtime",
  "# Implantação puramente nativa de streaming via escape hatch paralelo de infraestrutura CFN": "# Habilita o streaming (envio de respostas aos poucos) usando uma configuração especial do CloudFormation",
  "# Tabela de matriz atrelada isolada AWS DynamoDB focada em metadados puros unificados": "# Tabela do DynamoDB que vai guardar os metadados das sessões",
  "# Requisição isolada iterativa AWS GET de matriz /sessions": "# GET /sessions - Busca as sessões",
  "# Requisição orgânica AWS de persistência PUT /sessions/{sessionId}": "# PUT /sessions/{sessionId} - Salva ou atualiza uma sessão",
  "# Deleção estruturada atada da AWS pura DELETE": "# DELETE /sessions/{sessionId} - Apaga uma sessão",
  "# Resgate unificado orgânico atado do ecossistema via GET /history/{sessionId}": "# GET /history/{sessionId} - Pega o histórico da conversa",
  "# ----- Limpeza isolada atrelada orgânica puramente: garante que a topologia matriz possa ser expurgada -----": "# ----- Limpeza do workshop: garante que todos os recursos possam ser apagados no final -----",
  "# O framework CDK isolado remoto atrelado preserva (Retain) por padrão a Role atada do CloudWatch / Gateway.": "# O CDK por padrão não apaga a Role do CloudWatch do API Gateway (deixa como Retain).",
  "# Mutação do parâmetro estrito puro unificado da matriz atrelado para 'Delete' a fim de obliterar a malha limpamente.": "# Mudamos para Delete para que dê pra apagar tudo certinho no final do laboratório.",
  "# ----- Matriz de Exportações -----": "# ----- Exports -----",
  "# ----- Matrizes Variáveis de Contexto -----": "# ----- Variáveis de Contexto -----",
  "# ----- Matriz AWS S3 -----": "# ----- S3 Bucket -----",
  "# ----- Matriz de Distribuição CloudFront -----": "# ----- Distribuição do CloudFront -----",
  "# ----- Renderização unificada do config.js -----": "# ----- Geração do arquivo config.js -----",
  "# ----- Injeta arquivos puramente compilados atados remotos de Frontend via bucket S3 -----": "# ----- Envia os arquivos do frontend para o S3 -----",
  "# ----- Sincroniza matrizes URLs puras iterativas atadas de Callback com o endpoint blindado CloudFront -----": "# ----- Atualiza as URLs de callback do Cognito para usar a URL do CloudFront -----",
  "# Resolve a barreira de ciclo fechado: O template matriz puramente atrelado não possui visibilidade": "# Isso resolve um problema de dependência circular: o CloudFormation inicial não tem como",
  "# nativa orgânica do subdomínio AWS da CloudFront no ato da criação remota.": "# saber a URL do CloudFront antes dele ser criado.",
  "# ----- Variáveis de Retorno da AWS base -----": "# ----- Saídas (Outputs) -----",
  "# Mapeia o acervo na AWS de recursos isolados puros remotos nativos atados iterativos": "# Faz um levantamento de tudo que já foi criado na AWS",
  "# Obliterar a matriz iterativa unificada AWS seguindo fluxo logístico orgânico de reversa": "# Deleta os recursos na ordem inversa de dependência (do último pro primeiro)",
  "# Transmuta e purifica localmente o acervo matriz de registros .config": "# Limpa os arquivos de configuração locais",
  "# Exclui submissões isoladas orgânicas base atadas de Política Cedar puramente remoto antes": "# Apaga as políticas Cedar primeiro",
  "# Destrói targets embutidos isolados paralelos iterativos remotos primeiro na infra": "# Apaga os targets do gateway primeiro",
  "# --- Mapeia puramente o escopo isolado atrelado da nuvem AWS ---": "# --- Carrega as configurações atuais ---",
  "# --- Provisiona matriz OAuth unificada no núcleo AgentCore Runtime ---": "# --- Configura o OAuth no Runtime ---",
  "# --- Injeta o iterativo matriz endpoint atado /chat na rede ---": "# --- Adiciona a rota POST /chat ---",
  "# Rastreia idempotente orgânico iterativo a infra AWS para forçar POST na rota /chat": "# Garante que o método POST exista na rota /chat",
  "# Assegura integração apontada cirurgicamente nativa ao container ativo atual orgânico puro da rede": "# Garante que a integração aponte para o runtime atual",
  "# Libera subjacente atado streaming orgânico: 'ResponseTransferMode=STREAM' blinda paralelamente no API Gateway": "# Habilita o streaming: o 'ResponseTransferMode=STREAM' faz com que o API Gateway",
  "# o roteamento das matrizes em fluxo isolado puro à medida que o Agente da nuvem renderiza nativo": "# vá enviando os pedaços da resposta assim que o agente gera, ao invés de segurar tudo",
  "# o payload AWS atrelado base, evadindo timeouts subjacentes da AWS de 29s.": "# e mandar de uma vez (o que causaria timeout de 29s do API Gateway).",
  "# Aciona o compilador remoto orgânico atado de rede forçando mutação AWS unificada em produção": "# Cria um novo deploy para ativar as mudanças na API",
  "# --- Injeta iterativo ID puramente matricial da rede Memory no function Lambda paralelo de Histórico ---": "# --- Atualiza o Lambda de histórico com o ID da Memória ---",
  "# --- Forja orgânica paralela iterativa de UPLOAD remoto de estáticos S3 e script.js ---": "# --- Faz o upload dos arquivos do frontend e do config.js ---",
  "# Processo orgânico de submissão estrita remota do núcleo frontend AWS atrelado": "# Sobe os arquivos do frontend pro S3",
  "# Injete matriz atada gerada nativamente AWS de configurações do ecossistema iterativo puro config": "# Sobe o config.js gerado pro S3",
  "# --- Purga orgânica iterativa remota atada de malha de Edge Cache (CloudFront Invalidation) ---": "# --- Invalida o cache do CloudFront para mostrar a versão mais recente ---",
  "# --- Arquivamento de configuração unificada nativa na infra ---": "# --- Salva as configurações localmente ---",
  "# --- Renderização nativa atada interativa dos outputs AWS ---": "# --- Mostra os resultados na tela ---",
  "# Matriz estrita Auth puramente AWS IAM (Escopo restritivo nativo laboratório 02 ao 04)": "# Autenticação via IAM (Módulos 02 ao 04)",
  "# Autenticação via barramento estrito orgânico AWS OAuth/JWT (Iterativo contínuo Labs >= 05)": "# Autenticação via OAuth/JWT (Módulos 05 em diante)",
  "# Sistema de Credenciamento": "# Autenticação",
  "# Verifica subjacente remotamente atado a existência orgânica iterativa paralela do AWS User": "# Verifica se o usuário de teste já existe",
  "# Processo nativo AWS de invocação remota paralela da matriz do Agente via streaming AWS": "# Chamada do agente (com respostas em streaming)",
  "# Orquestrador iterativo sistêmico nativo da AWS REPL terminal": "# Loop de terminal (REPL) para você bater papo com o agente",
  "# Carrega a configuração nativa estruturada AWS provida iterativa do AgentCore Runtime": "# Carrega as configurações do runtime",
  "# Gatilho orgânico atrelado paralelo iterativo exigindo Auth nativa se estrito demandado": "# Autentica caso seja necessário",
  "# Empacota a esteira pura orgânica no container temporário isolado atado se arquivo manifest nativo requirements for encontrado": "# Instala as dependências numa pasta temporária se houver um requirements.txt",
  "# Rastrea e pareia as arquiteturas de OS, alinhando organicamente iterativo à CLI da nuvem matriz oficial": "# Tenta encontrar a versão certa da biblioteca de acordo com a arquitetura oficial do AgentCore",
  "# Expurgar infra base de construção iterativa atada nativa AWS paralela atrelada ao container isolado AWS temporário": "# Limpa a pasta temporária para tentar novamente, caso falhe",
  "# Injeta orgânico unificado atado camadas base de dependências na empacotadora paralela da nuvem AWS atada do zip build": "# Adiciona os arquivos das dependências no zip primeiro (ficam como camada base)",
  "# Indexa source do agente sobrepondo iterativo e mitigando atado conflitos de pacotes em submissão nativa remota": "# Adiciona os arquivos do próprio agente por cima (para sobrescrever se houver conflitos)",
  "# Purga de diretórios residuais iterativos da malha nativa AWS isolada orgânica providenciando lixo": "# Apaga a pasta temporária de dependências para manter tudo limpo",
  "# Bloqueio assíncrono iterativo orgânico atado nativo remoto AWS garantindo purificação": "# Aguarda até que o arquivo seja apagado com sucesso",
  "# Descoberta matriz nativa orgânica remota AWS interligada de saídas via AWS CFN Outputs atados providos puros": "# Descobre automaticamente os IDs e configurações via CloudFormation",
  "# Fluxo atado orgânico de empacotamento puramente 1: Package (Processo build AWS na matriz isolada atrelada)": "# Passo 1: Empacotar (Criar o zip com o código do agente)",
  "# Fluxo iterativo orgânico na nuvem puro de envio 2: Upload S3 (Armazena bucket orgânico paralelo remoto nativo atrelado da nuvem AWS pura)": "# Passo 2: Upload pro S3",
  "# Passos iterativos matriz 3: Instanciar atrelado na nuvem orgânica remota base AWS ou forçar Update provado atado remoto matriz AWS": "# Passo 3: Criar um novo runtime ou atualizar se já existir",
  "# Purificação nativa atrelada iterativa base matriz AWS: oblitera atado instâncias e metadados mortos remotos AWS da arquitetura matriz": "# 'Clean start': apaga qualquer runtime existente para evitar que configurações velhas atrapalhem",
  "# (Mitigando atado lixos estritos remotos de configuração JWT puramente atados AWS legados matriz AWS de sessões AWS provadas antigas atreladas de laboratórios prévios)": "# (Ex: Evitar que configurações antigas de JWT de um lab passado quebrem as coisas agora)",
  "# Topologia unificada base estrita AWS paramétrica": "# Parâmetros que são usados tanto na criação quanto na atualização",
  "# Matriz inabalável orgânica de sessão AWS viva de 15 minutos paralela": "# Mantém a sessão viva por 15 minutos em inatividade",
  "# Teto de nuvem de sessão extrema atada de limite AWS matriz 8h": "# Tempo máximo total da sessão de 8 horas",
  "# Preserve imperativo e intransponível matriz paralela orgânica a base config nativa iterativa": "# Mantém as configurações atuais do Runtime intactas",
  "# originada do deploy da UI orgânica, blindando contra obliteração nativa AWS paralela em caso de novo transbordo da nuvem.": "# (para que o deploy de um novo código não zere as configurações de autenticação JWT, por exemplo).",
  "# Gatekeeper nativo atado JWT da nuvem": "# Autorizador via JWT",
  "# Passagem de barreira iterativa 4: Suspensão em poll até AWS orgânico reportar READY": "# Passo 4: Fica de olho até o Runtime avisar que está pronto (READY)",
  "# Orquestra string atada nativa AWS do endpoint orgânico iterativo de invocação na matriz remota subjacente isolada da malha de infraestrutura interconectada": "# Monta a URL completa para fazermos chamadas pro agente",
  "# Consolida persistente matriz em disco para demais laboratórios": "# Salva as configurações num arquivo para os próximos labs lerem",
  "# Expurgar arquivo zip transitório puramente gerado em container atrelado": "# Apaga o arquivo zip temporário gerado localmente",
  "# Descritores de estrutura base matriz atrelada isolados na nuvem": "# Nomes e descrições dos recursos",
  "# Vetor matriz de acoplamentos puramente atados de dependência isolados iterativos em lote": "# Mapa de requisitos de cada módulo",
  "# Cada passo unificado na matriz atrelada especifica recursos estritos orgânicos AWS puramente atrelados": "# Cada módulo do curso diz quais recursos já devem estar rodando na AWS antes de começar",
  "# O parâmetro \"runtime\" demanda subjacente orgânico a implantação na malha do código agente iterativo em malha da nuvem orgânica puramente na arquitetura base nativa AWS paralela específica unificada atrelada da infra atada do laboratório iterativo correspondente": "# \"runtime\" é especial -- quer dizer que não basta qualquer runtime, é preciso que o",
  "# atestando transbordo em AWS iterativo atrelado remoto puramente, não tolerando apenas a checagem cega matriz iterativa unificada de um container genérico atado.": "# código do agente correspondente àquele módulo específico já esteja com deploy feito.",
  "# Check iterativo puramente na CFN (Pré-requisitos base AWS na matriz subjacente)": "# Módulo 00: Valida os pré-requisitos do CloudFormation",
  "# Ignorar infraestrutura remota isolada AWS atada puramente de validação (Introdução apenas)": "# Módulo 01: Introdução (nenhum recurso novo criado aqui)",
  "# Runtime (ponto de origem nativo atado da criação e orquestração orgânica matriz na AWS interativa)": "# Módulo 02: Onde criamos o Runtime pela primeira vez",
  "# Sandbox de Tools iterativas (necessita dependência de infra AgentCore na matriz AWS)": "# Módulo 03: Adicionando Ferramentas (requer o runtime já criado)",
  "# Memory (bloco lógico instanciará as bases LTM)": "# Módulo 04: Memória",
  "# Gestão e Acesso (matriz construirá nativo as rotinas de roteamento MCP remota na AWS)": "# Módulo 05: Gateway e Identidade",
  "# Cedar (fluxo de bloqueio atrelado blindará nativo na esteira iterativa as rotinas)": "# Módulo 06: Políticas de Acesso Cedar",
  "# Visão AWS Traces": "# Módulo 07: Observabilidade",
  "# Integração AWS Full Deploy nativo provado na matriz estrita final iterativa orgânica na matriz unificada na AWS paralela atada": "# Módulo 08: Deploy completo da aplicação",
  "# Matriz unificada nativa paralela de funções AWS atreladas de orquestração puramente atadas de forma idempotente emulada AWS base": "# Funções inteligentes de criação: elas só criam o recurso se ele não existir (são idempotentes)",
  "# Mapeia a infra orgânica AWS de identidades Cognito iterativo remoto nativo (Requisito iterativo da engine de rede isolada CUSTOM_JWT)": "# Busca os detalhes do Cognito gerados no CloudFormation (necessário pro login com CUSTOM_JWT)",
  "# Arquitetar Gateway nativo na malha interligada atada AWS da nuvem": "# Cria o Gateway",
  "# Aplica bloqueio orgânico atado de autoridade restrita iterativa CUSTOM_JWT puro nativo via Cognito, em alternativa forja atado remoto nativo AWS NONE": "# Se tiver Cognito configurado, usa CUSTOM_JWT, senão deixa liberado (NONE)",
  "# Embute matriz da REST Task API": "# Adiciona a API de Tarefas como um target no gateway",
  "# Monitora malha interconectada puramente iterativa atrelada à integridade do READY orgânico do target AWS base isolado iterativo remoto nativo da matriz atada": "# Aguarda até o Target ficar pronto e operante",
  "# Instancia infra nativa pura do Cedar Engine": "# Cria a engine do Policy",
  "# Dispara matriz isolada de restrições Cedar atomizadas iterativas nativo AWS atreladas": "# Cria as regras de acesso Cedar separadas por ação",
  "# Mesclar governança AWS pura atada isolada remoto iterativa de matriz paralela no Gateway AWS interconectado atrelado": "# Prende o motor de políticas lá no Gateway",
  "# Indexa matriz subjacente do repositório lógico do agente na matriz": "# Mapeia a pasta do código do agente referente a este módulo",
  "# Reutiliza atado o agente puro orgânico da fase iterativa atrelada AWS matriz 05": "# Reutiliza o código do agente da pasta 05",
  "# Clona iterativo a malha puramente do laboratório matriz atado 07 AWS isolada nativa": "# Reutiliza o código do agente da pasta 07",
  "# Para smart-recovery, aciona transbordo subjacente isolado da malha matriz orgânica unificada AWS do lab PRÉVIO atado puro": "# Quando estiver fazendo catch-up para um lab específico, ele vai fazer o deploy",
  "# (pois a matriz em foco puramente vai processar sua infra AWS restrita atada remotamente de deploy interligada)": "# do código do agente da versão imediatamente ANTERIOR àquele lab.",
  "# Valida estado orgânico atrelado iterativo liminar da nuvem matriz nativa paralela AWS Runtime base": "# Confere se o Runtime já está rodando e saudável",
  "# Roteamento atado da nuvem exige novo deploy matriz AWS interconectado puramente iterativo na matriz": "# Ops, precisamos fazer um novo deploy para seguir adiante",
  "# Forja variáveis de matriz orgânica operante paralela base do ambiente atrelado puro remoto iterativo da malha AWS isolada atada unificada": "# Constrói as variáveis de ambiente baseadas nos módulos que já foram configurados",
  "# Rota unificada iterativa AWS de Boot (Ponte de entrada da infraestrutura remota isolada puramente atada subjacente)": "# Ponto de entrada principal do script",
  "# Condicional puro AWS Memory base nativo": "# Especificamente para o módulo Memory",
  "# Avalia a saúde liminar puramente CFN": "# Sempre verifica se a base do CloudFormation está pronta",
  "# Valida iterativo a topologia de cada malha atada providenciada orgânica isolada e unificada da matriz base paralela na nuvem puramente atrelada estrita AWS da matriz isolada": "# Cria ou checa todos os recursos que a aula de hoje exige",
  "# Vetor atrelado puramente de rotas iterativas (id, label, config) na arquitetura matriz AWS paralela atrelada nativa da nuvem": "# Definições dos Módulos: (id, nome_amigável, verifica_se_esta_pronto)",
  "# Fluxo passivo AWS atado puramente atrelado (sem transbordo orgânico de componentes na nuvem atrelada matriz puramente nativa estrita)": "# Sem recursos passíveis de deploy nessa fase",
  "# Refinação nativa AWS dos outputs de massa interligada na matriz base orgânica puramente subjacente da infra": "# Abrevia valores muito longos pra não quebrar a tela do terminal",
  "# Havendo token matriz orgânico estrito iterativo AWS JWT, embute como header do payload orgânico atrelado isolado nativo AWS para orquestração remota ao AgentCore Gateway": "# Se tiver token JWT de login, envia ele no cabeçalho. Assim o AgentCore repassa ele adiante pro Gateway.",
  "# Ouve em malha paralela AWS a conexão iterativa e expurga em console os chunks estritos orgânicos recebidos puramente na malha atada AWS subjacente matriz iterativa estrita providenciando": "# Escuta a resposta e vai imprimindo na tela aos pouquinhos (stream) conforme o agente vai falando",
  "# Validação na malha de identidade atada puramente AWS Auth Cognito": "# Entrar no sistema",
  "# Registradores Constantes da Nuvem AWS": "# Constantes",
  "# Diretório nativo da nuvem unificada raiz atada isolada paralela": "# Diretório workshop-code/",
  "# Conjunto empacotado remoto auxiliar da infra AWS (Helpers da malha)": "# Funções auxiliares para lidar com a AWS",
  "# Invoca primariamente o mapeamento puramente remoto da pilha CloudFormation unificada atada da matriz orgânica AWS na raiz subjacente atrelada estrita": "# Primeiro tentamos procurar direto pelo nome oficial do stack do workshop",
  "# Contingência: Inspeciona orgânica todos os barramentos de CFN Stacks matriz na busca de assinaturas": "# Se não achar, varremos todas as stacks criadas pra ver se tem alguma com cara de ser a do curso",
  "# Sub-rotina nativa AWS atrelada da orquestração de persistência puramente matriz AWS atada de estado de disco (I/O remota)": "# Funções para salvar e ler os arquivinhos de configuração gerados em cada passo do lab",
  "# Interceptor auxiliar puramente unificado de estado AWS isolado matriz do Gateway remoto orgânico": "# Facilitador para pegar as configurações do Gateway",
  "# Controlador de loop assíncrono iterativo orgânico de matriz da nuvem para estados AWS unificados paralelos iterativos atados orgânicos (Waiters liminares puramente na AWS atada)": "# Função auxiliar para fazer polling (ficar perguntando pra AWS se um recurso já terminou de ser criado)",
  "# Inspeciona estritamente o json AWS atado puramente orgânico iterativo iterando unificado pelo target de payload da infra da rede atada remota iterativa da AWS": "# Navega dinamicamente dentro do dicionário de resposta da AWS para achar o status",
  "# Motor liminar de desserialização (Parser matriz orgânico puramente unificado AWS atado de Server-Sent Events interligados da infra paralela orgânica da rede da AWS)": "# Motor para processar Server-Sent Events (As respostas em pedaços do streaming)",
  "# Renderização atada das trilhas estritas em tempo puramente real base iterativa a partir dos buffers originais matriz orgânicos paralelos iterativos AWS": "# Pega o que tem de linha completa no buffer de texto e processa",
  "# Injeta na base de execução remota orgânica puramente subjacente unificada da rede AWS o flush matriz de sobras assíncronas do codificador assíncrono nativo iterativo AWS": "# Força qualquer sobra de bytes a ser processada pelo decodificador",
  "# Escoa nativa a estrutura residual do buffer iterativo atrelado remoto orgânico base da memória estrita AWS paralela nativa": "# Tira e processa tudo o que ainda sobrou preso no buffer de memória",
  "# Quebra de ponteiro nativa AWS estrita orgânica emulada puramente": "# Linha em branco",
  "# Rotina atada matriz orgânica unificada AWS de inspeção inicial puramente interativa de interceptação de anomalias (errores) na rede AWS atrelada paralela unificada nativa na matriz remota puramente paralela e ininterrupta da AWS iterativa atada": "# A primeira coisa é chegar se veio algum alerta de erro da AWS",
  "# Refinação puramente textual iterativa nativa paralela da AWS isolada atrelada base originada remotamente orgânica dos payloads puramente AWS (deltas puramente das matrizes AWS atadas remotas de interligação contínua da malha da rede unificada da nuvem)": "# Vai pegando e juntando só o pedaço da resposta de texto que o modelo gerou e mandou pra gente",
  "# Utilitários matrizes de visualização interligada unificada AWS da infraestrutura no terminal da rede": "# Utilitários para exibir caixas e divisórias bonitinhas no terminal",
  "# Coleção arquitetural atrelada puramente unificada e matriz compartilhada AWS das fundações nativas remotas orquestradas isoladas orgânicas contínuas paralelas atadas base originais puras da rede do curso AgentCore.": "# Conjunto de ferramentas compartilhadas utilizadas em todo o laboratório do Amazon Bedrock AgentCore."
}
