import json
import glob

mod04_06_translations = {
    # MODULE 4
    "# Module 4: AgentCore Memory -- Persistent Context": "# Módulo 4: AgentCore Memory -- Contexto Persistente",
    "In this module you will give Aria a **memory** so she can remember who you are across conversations.": "Neste módulo, você vai configurar a **memória** da Aria, permitindo que ela se lembre de quem você é ao longo de várias conversas.",
    "### What you will learn": "### O que você vai aprender",
    "| Topic | Details |": "| Tópico | Detalhes |",
    "| **AgentCore Memory service** | The managed memory layer that ships with Bedrock AgentCore |": "| **Serviço AgentCore Memory** | A camada gerenciada de memória nativa do Bedrock AgentCore |",
    "| **Short-term vs. long-term memory** | How STM (conversation buffer) and LTM (extracted knowledge) work together |": "| **Memória de curto vs. longo prazo** | Como o STM (buffer de conversa) e o LTM (conhecimento extraído) operam em conjunto |",
    "| **LTM extraction strategies** | Session summaries, user preferences, and semantic facts |": "| **Estratégias de extração LTM** | Resumos de sessão, preferências do usuário e fatos semânticos |",
    "| **Strands integration** | How `AgentCoreMemorySessionManager` plugs into a Strands agent |": "| **Integração com Strands** | Como o `AgentCoreMemorySessionManager` se conecta em um agente Strands |",
    "## Catch-up": "## Atualização de Dependências",
    "The cell below checks that every resource from previous modules is in place. If you skipped a module or something broke, it will fix things automatically.": "A célula abaixo valida se todos os recursos dos módulos anteriores estão ativos na AWS. Se você pulou alguma etapa, o script fará o provisionamento automaticamente.",
    "## Understanding Memory": "## Entendendo a Memória",
    "AgentCore Memory gives your agent the ability to **remember** information across sessions. It operates on two tiers:": "O AgentCore Memory concede ao seu agente a capacidade de **lembrar** informações entre as sessões. Ele opera em duas camadas:",
    "### Short-term memory (STM)": "### Memória de curto prazo (STM)",
    "When your agent sends conversation events to AgentCore Memory, the service stores them as **events**. These events capture each turn of the conversation. Your agent can retrieve these events to rehydrate its conversation history — useful if you want to resume a session later or carry on where you left off. Sending events to Memory is also what triggers the extraction of long-term memories (see below).": "Quando o agente envia eventos da conversa para o AgentCore Memory, o serviço os armazena como **eventos**. Eles capturam cada interação. O agente pode buscar esses eventos para reidratar o histórico da conversa — útil para retomar uma sessão posteriormente. Enviar eventos para o Memory também é o que ativa a extração das memórias de longo prazo.",
    "### Long-term memory (LTM)": "### Memória de longo prazo (LTM)",
    "Extracted knowledge that **persists across sessions**. As conversation events are sent to Memory during a session, the service runs extraction strategies in the background to distill the dialogue into durable knowledge. This extraction typically takes around a minute. The extracted memories can be retrieved within the same conversation if it runs long enough, but the primary purpose is to provide context in **future sessions**. When a new session starts, relevant LTM is retrieved and injected into the agent's context.": "Conhecimento extraído que **persiste entre as sessões**. À medida que os eventos são enviados, o serviço executa estratégias de extração em segundo plano (background) para transformar o diálogo em conhecimento durável. Essa extração leva cerca de um minuto. O objetivo principal é fornecer contexto para as **futuras sessões**.",
    "AgentCore Memory supports three LTM extraction strategies:": "O AgentCore Memory suporta três estratégias nativas de extração LTM:",
    "| Strategy | Class | Namespace | Purpose |": "| Estratégia | Classe | Namespace | Propósito |",
    "| **Session Summarizer** | `summaryMemoryStrategy` | `/summaries/{actorId}/{sessionId}` | Creates a concise summary of the conversation so future sessions can quickly recall what was discussed |": "| **Session Summarizer** | `summaryMemoryStrategy` | `/summaries/{actorId}/{sessionId}` | Cria um resumo conciso da sessão para ser recuperado rapidamente no futuro |",
    "| **Preference Learner** | `userPreferenceMemoryStrategy` | `/preferences/{actorId}` | Detects and stores user preferences (e.g., \"I prefer Python over Java\") |": "| **Preference Learner** | `userPreferenceMemoryStrategy` | `/preferences/{actorId}` | Detecta e armazena preferências do usuário (ex: 'Prefiro Python a Java') |",
    "| **Fact Extractor** | `semanticMemoryStrategy` | `/facts/{actorId}` | Extracts factual statements (e.g., \"I work at Acme Corp\", \"My name is Alex\") |": "| **Fact Extractor** | `semanticMemoryStrategy` | `/facts/{actorId}` | Extrai informações factuais (ex: 'Trabalho na Acme Corp', 'Meu nome é Alex') |",
    "Each strategy writes to its own **namespace** and the `{actorId}` placeholder is replaced at runtime with the authenticated user's identity, keeping each user's memories isolated.": "Cada estratégia grava em seu próprio **namespace**, e o `{actorId}` é substituído dinamicamente em tempo de execução pela identidade do usuário autenticado, mantendo as memórias de cada usuário totalmente isoladas.",
    "### Create the Memory resource": "### Criando o recurso Memory na AWS",
    "The `create_memory` API provisions a **memory resource** — think of it as creating a place where memories will be stored, not creating an actual memory of a fact. The memory resource is essentially a managed data store backed by DynamoDB.": "A API `create_memory` provisiona um **recurso de memória** — pense nisso como a criação do repositório onde as memórias serão armazenadas. Este recurso é um banco de dados gerenciado com base no DynamoDB.",
    "You _can_ set up a memory resource without any LTM strategies at all. In that case, it simply stores conversation events (acting as a wrapper for DynamoDB). LTM strategies are optional add-ons that extract knowledge from those stored events.": "Você _pode_ configurar um recurso sem nenhuma estratégia LTM. Nesse caso, ele apenas armazena os eventos do chat. As estratégias LTM são complementos opcionais que extraem o conhecimento orgânico.",
    "Here we configure all three strategies so Aria gets the full memory experience:": "Aqui configuramos as três estratégias para a Aria ter a experiência completa:",
    "- **SessionSummarizer** — Summarizes conversations when a session ends": "- **SessionSummarizer** — Resume as conversas quando a sessão é encerrada",
    "- **PreferenceLearner** — Extracts user preferences (\"I prefer dark mode\")": "- **PreferenceLearner** — Extrai preferências corporativas ('Prefiro modo escuro')",
    "- **FactExtractor** — Stores semantic facts (\"Alex is a software engineer\")": "- **FactExtractor** — Armazena fatos semânticos puros ('Alex é engenheiro de software')",
    "Each strategy has:": "Cada estratégia possui:",
    "- A **name** and **description** for identification": "- Um **name** (nome) e **description** (descrição) para identificação",
    "- **Namespaces** — template paths that scope stored memories (e.g., per user, per session)": "- **Namespaces** — caminhos de template que delimitam o escopo das memórias (por usuário ou por sessão)",
    "### Wait for the Memory resource to become ACTIVE": "### Aguardando o status ACTIVE do Memory",
    "Memory creation is asynchronous. We poll until the status reaches `ACTIVE`.": "A criação da memória é assíncrona. Fazemos polling da API até o status ficar `ACTIVE`.",
    "### Save the Memory ID for later modules": "### Salvando o ID do Memory",
    "We persist the memory ID to the shared config directory so that `ensure_ready()` and deployment helpers can find it in subsequent modules.": "Persistimos o ID do Memory no diretório local de configuração para que o `ensure_ready()` e os scripts de deploy o encontrem nos módulos seguintes.",
    "## Enable Tracing for Memory": "## Habilitar Tracing (Observabilidade) para a Memória",
    "Enable **Tracing** on the Memory resource so that memory operations (store, retrieve, extraction) appear in the AgentCore Observability dashboard.": "Habilite o **Tracing** no recurso Memory para que as operações de leitura e gravação apareçam no painel do AgentCore Observability.",
    "1. Open the **Amazon Bedrock AgentCore** console and navigate to **Memory**": "1. Abra o console do **Amazon Bedrock AgentCore** e navegue até **Memory**",
    "2. Select the **AriaMemory** resource": "2. Selecione o recurso **AriaMemory**",
    "3. Scroll down to the **Tracing** section and click **Edit**": "3. Role para a seção **Tracing** e clique em **Edit**",
    "4. Toggle **Enable** on and click **Save**": "4. Ative a chave **Enable** e clique em **Save**",
    "## Deploy with Memory": "## Deploy com o módulo Memory ativado",
    "We redeploy Aria with the `MEMORY_ID` environment variable pointing to the Memory resource we just created. The runtime will pick up the new agent code **and** the memory configuration.": "Vamos fazer o deploy da Aria com a variável de ambiente `MEMORY_ID` apontando para a Memória que acabamos de provisionar. O Runtime carregará o novo código e a nova configuração.",
    "## Test Memory: Conversation 1": "## Testando a Memória: Conversa 1",
    "Let's have a conversation where we tell Aria some facts and preferences. Both messages use the **same session ID** so they share the conversation buffer (STM).": "Vamos ter uma conversa onde passaremos alguns fatos para a Aria. Ambas as mensagens usam a **mesma sessão (session ID)**, compartilhando o buffer de curto prazo (STM).",
    "### Tell Aria about yourself": "### Fale sobre você para a Aria",
    "### Same session -- STM recall (conversation buffer)": "### Mesma sessão -- Recuperação de STM (curto prazo)",
    "Aria should recall your name and preferences because the first message is still in the conversation buffer.": "Aria deve conseguir lembrar seu nome, já que a primeira mensagem ainda está ativa na sessão da microVM.",
    "## Test Memory: New session (LTM recall)": "## Testando a Memória: Nova sessão (Longo Prazo)",
    "Now we start a **brand-new session**. The conversation buffer is empty, so Aria can only recall facts if the LTM extraction strategies have processed the previous conversation and stored your preferences and facts.": "Agora iniciaremos uma **nova sessão**. O buffer de conversa estará limpo, então a Aria só vai se lembrar dos seus dados se o LTM (longo prazo) tiver extraído os fatos com sucesso na AWS.",
    "> **Note:** LTM extraction happens in the background as conversation events are sent to Memory. It typically takes around a minute for memories to be formed and saved. If the new session returns no memories, wait 30--60 seconds and try again.": "> **Nota:** A extração para o LTM roda em background (segundo plano). Geralmente leva cerca de 1 minuto. Se a nova sessão falhar em lembrar de você de primeira, aguarde 60 segundos e rode a célula novamente.",
    "If everything is working, Aria should recall that your name is Alex, that you are a software engineer, and that you prefer Python over Java -- even though this is a completely new session.": "Se a arquitetura estiver correta, a Aria lembrará do seu nome, sua profissão e sua preferência por Python — mesmo em um chat novo.",
    "## How it works": "## Como a arquitetura funciona",
    "Here is the end-to-end flow:": "Aqui está o fluxo operacional da arquitetura:",
    "- The session starts, or restarts. AgentCoreMemorySessionManager retrieves message events if they exist for this session. ": "- A sessão é iniciada. O AgentCoreMemorySessionManager busca os eventos na AWS (se já existirem).",
    "- User enters a message. ": "- O usuário digita a mensagem.",
    "- AgentCoreMemorySessionManager performs a LTM query of AgentCore Memory and returns semantically related memories. They get prepended to message before sending to agentic loop.": "- O AgentCoreMemorySessionManager faz uma query no LTM e retorna memórias ligadas semanticamente, injetando esse contexto no loop do agente.",
    "- Agent processes messages.": "- O Agente processa a inferência.",
    "- All messages, including generated messages are sent via AgentCoreMemorySessionManager to AgentCore Memory as events.": "- Todas as interações são disparadas como eventos na AWS via AgentCoreMemorySessionManager.",
    "- AgentCore Memory runs extraction strategies in the background to distill the conversation into durable knowledge. The extracted memories are stored in the configured namespaces.": "- A AWS (AgentCore Memory) executa a rotina de extração em background para destilar as informações duráveis nos namespaces.",
    "The retrieval configs use different thresholds because:": "As configurações de threshold (limite de busca semântica) são diferentes:",
    "- **Preferences** (`relevance_score=0.7`): Only highly relevant preferences should influence responses": "- **Preferências** (`relevance_score=0.7`): Exige alta relevância de busca.",
    "- **Facts** (`relevance_score=0.3`, `top_k=10`): Cast a wider net to bring in background knowledge": "- **Fatos** (`relevance_score=0.3`, `top_k=10`): Busca mais abrangente para compor o contexto geral.",
    "- **Summaries** (`relevance_score=0.5`): Balance between relevance and coverage of past conversations": "- **Resumos** (`relevance_score=0.5`): Um equilíbrio entre os dois pólos.",
    "## What's next": "## Próximo Passo",
    "Memory gives Aria a brain -- she can remember who you are and what you care about. But right now she can only **chat**. She cannot interact with external systems on your behalf.": "A Memória deu um cérebro duradouro para a Aria. Mas no momento, ela só sabe **conversar**. Ela não consegue manipular sistemas externos por você.",
    "In **Module 5: Gateway & Identity**, we will connect Aria to a Task Management API through AgentCore Gateway, and use JWT-based identity so each user's tasks stay private.": "No **Módulo 5: Gateway e Identidade**, vamos conectar a Aria a uma API de Tarefas através do AgentCore Gateway e aplicar proteção JWT para garantir o isolamento da identidade corporativa.",

    # MODULE 5
    "# Module 5: Gateway & Identity -- Connecting External APIs": "# Módulo 5: Gateway e Identidade -- Conectando APIs Externas",
    "In this module you will give Aria the ability to **manage tasks** by connecting her to an external REST API through AgentCore Gateway, with JWT-based identity so every user's data stays private.": "Neste módulo, você dará à Aria a habilidade de **gerenciar tarefas** conectando-a a uma REST API através do AgentCore Gateway, implementando segurança de identidade JWT.",
    "| **AgentCore Gateway** | An MCP endpoint that routes agent tool requests to backend APIs |": "| **AgentCore Gateway** | Um endpoint MCP gerenciado que roteia chamadas de ferramentas para o backend |",
    "| **MCP protocol** | How Gateway auto-discovers API structure and exposes it as MCP tools |": "| **Protocolo MCP** | Como o Gateway descobre e expõe a estrutura da sua API como ferramentas MCP |",
    "| **Identity & JWT auth** | How `CUSTOM_JWT` auth validates user tokens against Cognito |": "| **Identidade e Auth JWT** | Como o modo `CUSTOM_JWT` valida tokens no AWS Cognito |",
    "| **End-to-end identity flow** | User JWT flows from Runtime through Gateway to the target API |": "| **Fluxo de identidade** | O caminho percorrido pelo JWT, desde o Runtime até a API final |",
    "The cell below ensures all resources from previous modules (Runtime, Memory) are in place.": "Esta etapa garante que os recursos na nuvem (Runtime, Memory) estejam em perfeita execução.",
    "## Understanding Gateway": "## A Arquitetura do Gateway",
    "AgentCore Gateway is a **managed MCP endpoint** that sits between your agent and backend APIs. Instead of writing custom tool code for every API, you point Gateway at a backend service and it:": "O AgentCore Gateway é um **endpoint gerenciado MCP** posicionado entre a IA e as APIs. Em vez de criar código de ferramenta (tool) para cada API, você aponta o Gateway para o serviço e ele:",
    "1. **Auto-discovers** the API structure (paths, methods, parameters)": "1. **Auto-descobre** a estrutura REST (rotas, métodos, schemas)",
    "2. **Generates MCP tools** that your agent can call (e.g., `list_tasks`, `create_task`)": "2. **Gera ferramentas MCP dinâmicas** para a IA (`list_tasks`, `create_task`)",
    "3. **Handles authentication** between the agent and the target API": "3. **Orquestra a autenticação** na ponte entre o agente e o alvo",
    "4. **Routes requests** to the target using IAM credentials from the Gateway's execution role": "4. **Roteia as requisições** disparando com credenciais AWS IAM puras",
    "### Target types": "### Tipos de Targets Suportados",
    "Gateway supports five types of backend targets:": "O Gateway aceita cinco tipos de provedores backend (targets):",
    "| Target Type | Description |": "| Target | Descrição do Ambiente AWS |",
    "| **Lambda** | Invoke a Lambda function directly |": "| **Lambda** | Invoca uma função AWS Lambda de forma direta |",
    "| **API Gateway** | Auto-discover an API Gateway REST API (what we use in this module) |": "| **API Gateway** | Descoberta automática de um API Gateway da AWS |",
    "| **OpenAPI** | Provide an OpenAPI spec for any HTTP endpoint |": "| **OpenAPI** | Ingestão manual de um manifesto OpenAPI/Swagger |",
    "| **Smithy** | Provide a Smithy model definition |": "| **Smithy** | Modelagem Smithy corporativa |",
    "| **MCP server** | Connect to another MCP-compatible server |": "| **Servidor MCP** | Conecta dinamicamente a outro servidor MCP (Model Context Protocol) |",
    "### Authentication modes": "### Modos de Autenticação",
    "Gateway supports multiple authentication modes for validating inbound requests:": "O Gateway suporta esses padrões operacionais de auth:",
    "| Auth Mode | Use Case |": "| Modo | Cenário AWS |",
    "| `NONE` | Public APIs or development/testing |": "| `NONE` | APIs públicas, dev local e laboratórios liminares |",
    "| `CUSTOM_JWT` | User-facing APIs where each request carries a JWT identifying the user |": "| `CUSTOM_JWT` | Chamadas em que a identidade de ponta a ponta do cliente carrega um JWT |",
    "| `AWS_IAM` | AWS service-to-service authentication |": "| `AWS_IAM` | Comunicação M2M assinalada pela AWS (Service-to-service) |",
    "In this module we use `CUSTOM_JWT` backed by Amazon Cognito.": "Aqui usaremos a malha estrita do `CUSTOM_JWT` gerada via Amazon Cognito.",
    "> **Note:** This module introduces **JWT-based authentication**. Up to now, all agent invocations used IAM (SigV4) authentication. From this point forward, the agent will validate user identity via JWT tokens — this is what enables per-user isolation in Gateway and (in Module 6) policy enforcement.": "> **Nota Operacional:** Deste laboratório em diante, o agente passará a exigir JWT em suas invocações. É esse JWT que blinda e isola a arquitetura no backend.",
    "## Understanding Identity": "## Entendendo a Propagação de Identidade",
    "When you enable `CUSTOM_JWT` authentication on a Gateway, the identity flow works like this:": "No modo `CUSTOM_JWT`, o barramento flui assim na rede:",
    "1. **User authenticates** with Cognito and receives a JWT (ID token)": "1. O usuário faz o Login e o **Cognito emite um JWT**",
    "2. **Agent Runtime** receives the JWT in the `Authorization` header": "2. O AgentCore Runtime **recebe o header Authorization** com o token",
    "3. **Agent code** forwards the JWT to Gateway via the MCP client": "3. O código da Aria **repassa esse JWT** no cliente MCP",
    "4. **Gateway validates** the JWT against the Cognito OIDC discovery endpoint": "4. O Gateway bate no OIDC da Cognito e **valida as chaves do JWT**",
    "5. **Gateway calls** the target API using its own IAM role credentials": "5. O Gateway **chama a REST API alvo** usando sua Role segura do IAM",
    "This means the target API receives requests authenticated by IAM (from the Gateway role), while the Gateway itself knows **who** the user is from the JWT. The agent code also decodes the JWT to extract the `sub` claim as an `actor_id` for Memory namespace isolation.": "A API de destino fica protegida e só aceita o IAM do Gateway, enquanto o Gateway sabe de forma absoluta **quem** está logado. Extraímos também o `sub` do JWT para ser o `actor_id` da Memória da AWS.",
    "In **Module 6** we will add Cedar policies to Gateway that use this JWT identity to enforce per-user access control.": "Isso nos prepara para o **Módulo 6**, onde o Cedar bloqueará ações com base neste JWT.",
    "## Gather prerequisites": "## Coletando variáveis da Infraestrutura",
    "We need several values from the CloudFormation prerequisites stack: the Gateway IAM role, the REST API ID for the Task API, and Cognito details for JWT authentication.": "Precisamos coletar os IDs gerados pela stack do CloudFormation (Roles do IAM, ID da REST API e o provedor do Cognito).",
    "## Create the Gateway": "## Instanciando o Gateway",
    "The `create_gateway` API sets up a managed MCP endpoint. We configure:": "Usaremos a API `create_gateway` para subir esse componente. Configuramos:",
    "- **`protocolType: MCP`** -- the gateway speaks the Model Context Protocol": "- **`protocolType: MCP`** -- Comunicação no padrão da indústria",
    "- **`authorizerType: CUSTOM_JWT`** -- every request must carry a valid JWT": "- **`authorizerType: CUSTOM_JWT`** -- Bloqueio e exigência do token JWT",
    "- **`discoveryUrl`** -- points to the Cognito OIDC well-known endpoint so Gateway can validate tokens": "- **`discoveryUrl`** -- O caminho da nuvem OIDC para validação das chaves RSA",
    "- **`allowedAudience`** -- restricts which Cognito app client IDs are accepted": "- **`allowedAudience`** -- Valida a audiência rigorosa (ID do App Client)",
    "### Wait for Gateway to become READY": "### Aguardando o Gateway operar",
    "Gateway creation is asynchronous. We poll until the status reaches `READY` and capture the gateway URL.": "O deploy de um Gateway é assíncrono. O polling aguardará o estado de `READY`.",
    "## Add the Task API target": "## Embutindo o Target da API",
    "A Gateway **target** connects the MCP endpoint to a backend API. We point it at the API Gateway REST API from the prerequisites stack.": "Um **target** do Gateway aponta o MCP para um serviço que realmente exista. Ligaremos na REST API que foi provisionada na stack original.",
    "Key configuration:": "Ponto chave da configuração:",
    "- **`apiGateway`** — tells Gateway to **auto-discover** the REST API structure from the given `restApiId` and `stage`. Gateway inspects the API's resources, methods, and models to generate MCP tools automatically.": "- **`apiGateway`** — Faz a descoberta automática via `restApiId`.",
    "- **`toolOverrides`** — customizes the auto-discovered tools with clearer names and descriptions so the agent understands what each tool does. Without overrides, tool names are generated from HTTP method + path (e.g., `get_tasks`).": "- **`toolOverrides`** — Renomeia de maneira semântica as ferramentas (tools) mapeadas para facilitar a interpretação pela IA.",
    "- **`toolFilters`** — restricts which API paths/methods are exposed as tools (defense in depth)": "- **`toolFilters`** — Filtra as rotas liberadas por segurança estrita.",
    "- **`GATEWAY_IAM_ROLE`** — outbound calls to the target API use the Gateway's IAM role": "- **`GATEWAY_IAM_ROLE`** — Credencial IAM remota outboud que o Gateway assumirá.",
    "### Save Gateway config for later modules": "### Salvando a Configuração do Gateway",
    "## Enable Tracing for Gateway": "## Habilitando Observabilidade (Tracing) no Gateway",
    "Enable **Tracing** on the Gateway resource so that MCP tool requests and policy evaluations appear in the AgentCore Observability dashboard.": "Ligue o modo **Tracing** para que as chamadas das ferramentas MCP surjam no CloudWatch e painel de Observabilidade.",
    "1. Open the **Amazon Bedrock AgentCore** console and navigate to **Gateways**": "1. Abra o console do **Amazon Bedrock AgentCore** e clique em **Gateways**",
    "2. Select the **aria-gateway** resource": "2. Selecione o nosso **aria-gateway**",
    "## Deploy with Gateway": "## Deploy com Gateway Acoplado",
    "We redeploy Aria with both the `MEMORY_ID` (from Module 4) and the new `GATEWAY_ENDPOINT` environment variables.": "Vamos disparar um novo pacote do agente contendo as variáveis ambientais da `MEMORY_ID` e o novo `GATEWAY_ENDPOINT`.",
    "## Test Task Management": "## Testando a Gestão de Tarefas (Target API)",
    "Now let's use Aria's new task management capabilities. Since Gateway uses `CUSTOM_JWT` auth, we first get a JWT token, then use the shared `test_agent` helper to invoke Aria.": "O Gateway utiliza o `CUSTOM_JWT`. Logo, precisamos injetar o token JWT na rotina de teste `test_agent`.",
    "### List all tasks": "### Listar tarefas",
    "### Mark a task as completed": "### Atualizar Tarefa para concluída",
    "### Try it interactively": "### Terminal Interativo",
    "You can also test Aria with the CLI chat client. Since we now have JWT authentication, use the `--auth` flag:": "Você pode abrir o CLI para conversar. Como agora temos Auth forte na AWS, passe a flag `--auth`:",
    "Try creating, listing, and completing tasks through natural conversation.": "Tente criar ou ler as tarefas de forma orgânica e conversacional.",
    "## What's next": "## E agora?",
    "Gateway connects Aria to external APIs with full identity propagation. But right now, **any authenticated user can do anything** -- create tasks, delete tasks, access any endpoint.": "O Gateway está operante! A falha arquitetural do momento é: **qualquer pessoa logada pode fazer qualquer coisa** -- criar, deletar e bagunçar todas as APIs do endpoint.",
    "In **Module 6: Policy**, we will add **Cedar policies** to Gateway that control exactly which actions each user is permitted to perform.": "No **Módulo 6: Política**, aplicaremos as **Políticas Cedar** no Gateway como um escudo impenetrável de regra de negócio.",

    # MODULE 6
    "# Module 6: Cedar Policies -- Deterministic Guardrails": "# Módulo 6: Políticas Cedar -- Regras de Negócio e Barreiras (Guardrails)",
    "In this module, you will add **Cedar policies** to Aria's Gateway using the AgentCore Policy service. Unlike prompt-based guardrails that rely on the LLM to comply, Cedar policies are **deterministic** -- they evaluate at the Gateway boundary, outside agent code, with 100% reliability.": "Este laboratório acopla as **Políticas Cedar** de barreira estrita e impenetrável no Gateway. Diferente de avisos inseridos em texto que dependem que a IA cumpra a regra, as regras Cedar são **determinísticas** -- executadas na rede externa da API de forma 100% segura, antes mesmo da ferramenta rodar.",
    "There is no new agent code for this module. Aria continues to run V4 from Module 5. The focus here is entirely on the policy layer.": "Não há código extra de agente no Módulo 6. O deploy será apenas focado em infraestrutura de acesso de rede AWS.",
    "- **AgentCore Policy**: How to create a Policy Engine and attach it to a Gateway": "- **AgentCore Policy**: Orquestrar e acoplar um motor Cedar ao Gateway.",
    "- **Cedar language**: The `permit(principal, action, resource) when { conditions }` syntax": "- **Sintaxe Cedar**: A matriz técnica de liberação explícita `permit(...)`.",
    "- **Deterministic guardrails**: Why policies are more reliable than prompt-based rules": "- **Blindagem Determinística**: O bloqueio puramente de infra na nuvem que não cede à IA.",
    "- **Business rules**: Enforcing that tasks cannot be created with status \"completed\"": "- **Regra de Negócio**: Impedir que tarefas já sejam forjadas na nuvem como 'concluídas'.",
    "- **ENFORCE vs LOG_ONLY**: Choosing the right enforcement mode": "- **ENFORCE vs LOG_ONLY**: Modo restritivo (Deny) e modo observacional.",
    "The following cell ensures all prerequisites from earlier modules are in place. If you completed Modules 0-5, this will verify everything. If you skipped ahead, it will create the missing resources automatically.": "Esse bloco checa e executa qualquer módulo que tenha sido corrompido nos laboratórios passados.",
    "## Why deterministic policies?": "## A Importância do Determinismo nas Políticas AWS",
    "Consider two approaches to enforcing the rule *\"users cannot create tasks that are already marked completed\"*:": "Observe duas formas de proibir que \"usuários criem tarefas concluídas\":",
    "| Approach | How it works | Reliability |": "| Abordagem | Funcionamento | Nível de Confiabilidade |",
    "| **Prompt-based** | Add to system prompt: \"Never create a task with status completed\" | Probabilistic -- the LLM *usually* follows instructions, but can be jailbroken or simply forget |": "| **Via Prompt** | Escrito no System Prompt: \"Não faça isso...\" | Probabilístico -- a IA geralmente obedece, mas pode sofrer jailbreaks (ataques) ou simplesmente ignorar a instrução por não estar treinada |",
    "| **Cedar policy** | `permit(...) unless { action is create_task and status is completed }` | Deterministic -- the Gateway evaluates the policy *before* the request reaches the API. 100% reliable. |": "| **Cedar Policy (AWS)** | Código restritivo na malha | Determinístico -- O Gateway intercepta e barra a requisição de rede *antes* dela chegar no banco de dados. 100% à prova de falhas! |",
    "Cedar policies evaluate at the **Gateway boundary**, completely outside the agent's code and the LLM's reasoning loop. The agent never even sees a denied request -- the Gateway blocks it before it reaches the target API.": "O Cedar é avaliado nativo na nuvem fora da IA (no escopo da rede AWS). O agente IA apenas receberá uma resposta da AWS de acesso negado.",
    "This is the same Cedar language used by [Amazon Verified Permissions](https://aws.amazon.com/verified-permissions/) and is purpose-built for authorization decisions.": "É a mesmíssima linguagem adotada no Amazon Verified Permissions.",
    "## Understanding Cedar": "## Entendendo a Sintaxe Cedar",
    "Cedar policies follow a **principal / action / resource** model with conditions:": "O código Cedar é avaliado sob a arquitetura principal/action/resource:",
    "### Key concepts": "### Tópicos chave de Segurança",
    "- **Default deny** -- Cedar denies any request that is not explicitly permitted. Each tool action needs its own `permit` policy.": "- **Bloqueio por padrão (Default Deny)** -- Cedar bloqueia TUDO a menos que você conceda `permit` explícito.",
    "- **Actions** are named using the pattern `<target-name>___<tool-name>`, matching the tool names defined in your Gateway target's `toolOverrides`. For our task API: `TaskApi___list_tasks`, `TaskApi___create_task`, `TaskApi___update_task`, `TaskApi___delete_task`": "- **Ações (Actions)** seguem o formato de endpoint. O mapeamento é `<target>___<tool_name>`.",
    "- **Resource** is the Gateway ARN: `AgentCore::Gateway::\"<ARN>\"`": "- **Recurso (Resource)** apontado e restrito ao ID da ARN da AWS.",
    "- **Conditions** use `context.input` to inspect the request body fields. Every policy requires a `when` condition that references `context.input` -- the Policy Engine rejects unconditional permits as overly broad.": "- **Condições** filtram os bytes da requisição usando `context.input`.",
    "- **Sentinel conditions** -- For policies that should allow all requests, use a condition that is always true: `!(context.input has field && context.input.field == \"__blocked__\")`. This satisfies the validator while never actually blocking anything.": "- **Condições Fantasmas (Sentinelas)** -- Como a AWS rejeita permissões 'abertas' sem checagens de input (evitando brechas de segurança amplas), nós devemos forjar condições sempre-verdadeiras `!(__blocked__)` para permitir ações.",
    "### The business rule": "### A nossa regra corporativa de Negócio",
    "Tasks cannot be CREATED with status \"completed\". They must start as \"pending\" or \"in_progress\" and transition through an update. This enforces a proper task lifecycle.": "As tarefas **NÃO PODEM** ser forjadas e salvas diretamente no modo 'Concluído'. É imperativo que transitem num ciclo de vida correto.",
    "## Setup": "## Início da Configuração (Setup)",
    "First we connect to the AgentCore control plane and load the Gateway configuration from Module 5.": "Vamos recuperar o nosso Gateway do Módulo 5.",
    "## Create the Policy Engine": "## Instanciando o AWS Policy Engine",
    "A Policy Engine is the container that holds Cedar policies and evaluates them against incoming requests. We create one and wait for it to become ACTIVE.": "É o Motor restritivo Cedar na infraestrutura da AWS. Sobe e aguardamos o ACTIVE.",
    "## Create Cedar policies": "## Injeção das Políticas Cedar",
    "Cedar's **default deny** means every tool action needs an explicit permit. We need four policies -- one per Gateway tool:": "Como o Cedar nega tudo por padrão, enviaremos as quatro regras isoladas do Gateway:",
    "| Policy | Action | Condition |": "| Regra (Policy) | Ação da API | Condição Analisada |",
    "| `permit_list_tasks` | `TaskApi___list_tasks` | Block when `status == \"completed\"` |": "| `permit_list_tasks` | `TaskApi___list_tasks` | Bloqueia se a requisição procurar concluídas |",
    "| `permit_create_task` | `TaskApi___create_task` | Block when `status == \"completed\"` |": "| `permit_create_task` | `TaskApi___create_task` | Bloqueia se criar tarefa já com status concluída |",
    "| `permit_update_task` | `TaskApi___update_task` | Allow all (sentinel condition) |": "| `permit_update_task` | `TaskApi___update_task` | Aberta (com a cláusula fantasma AWS) |",
    "| `permit_delete_task` | `TaskApi___delete_task` | Allow all (sentinel condition) |": "| `permit_delete_task` | `TaskApi___delete_task` | Aberta (com a cláusula fantasma AWS) |",
    "The `create_task` and `list_tasks` policies enforce the business rule: tasks cannot be created (or filtered) with status \"completed\". The `update_task` and `delete_task` policies permit all operations.": "Com isso a gente blinda a criação indevida, mas deixa que a tarefa seja atualizada.",
    "> **Important:** Every policy requires a `when` condition that references `context.input`. The Policy Engine rejects unconditional permits as overly broad. For policies that should allow all requests, use a sentinel condition that is always true (e.g., `!(context.input has field && context.input.field == \"__blocked__\")`).": "> **Aviso Importante AWS:** Lembre-se, o motor de políticas restritivas vai barrar se a sua regra Cedar for ampla demais. Sempre aplique as condições Sentinelas descritas acima.",
    "### NL2Cedar: generating policies from natural language": "### NL2Cedar: Engenharia Automática de Regras com IA GenAI",
    "AgentCore Policy also supports **NL2Cedar** -- an API that translates plain-English descriptions into Cedar policies. Instead of writing Cedar by hand, you describe the intent:": "Um superpoder interno da AWS. Em vez de você escrever aquele código todo manual, você passa pra nuvem uma String de instrução de segurança: 'Deixe o meu time de Suporte pedir reembolsos só até 500 dólares', e a AWS cria a política pronta pra ti.",
    "NL2Cedar analyzes the Gateway's tools and input schemas to produce valid Cedar with the right action names and `context.input` conditions. This is particularly useful when policies have complex conditions that are easier to express in natural language than in Cedar syntax.": "O NL2Cedar consome o manifesto e traduz para as cláusulas rigorosas de validação de payload em Cedar de forma transparente.",
    "## Attach Policy Engine to Gateway": "## Interligando e Blindando o Gateway",
    "Now we attach the policy engine to the Gateway in **ENFORCE** mode. This means any request that violates a policy will be **denied** -- the agent will receive an error instead of the tool result.": "Vamos plugar esse motor Cedar diretamente no Gateway. Ligaremos o modo **ENFORCE** (Imposição Extrema da Restrição). O agente receberá o erro sem sucesso de burlar a máquina.",
    "### Wait for Gateway to update": "### Aguardando Atualização Remota",
    "### Save configuration": "### Salvar Configuração",
    "## Test Cedar policy enforcement": "## Laboratório Prático da Restrição Cedar",
    "Let's test the policies. We use the shared `test_agent` helper with a JWT token. Each invocation flows through:": "Vamos tentar ser espertos usando a função `test_agent`. Tudo será repassado pela infra AWS de Cedar.",
    "### Test 1: Create a task with status \"completed\" -- should be DENIED": "### Teste 1: Mandar criar uma Tarefa e já marcá-la 'Concluída' -- Será BLOQUEADO PELA AWS",
    "This request explicitly asks to create a task with status \"completed\". The `permit_create_task` policy blocks this because the condition `!(context.input has status && context.input.status == \"completed\")` evaluates to false.": "O Cedar vai avaliar `status == completed` de dentro da payload e o processo será estritamente vetado antes da nuvem executar.",
    "### Test 2: Create a task without specifying status -- should SUCCEED": "### Teste 2: Criar tarefa normal pendente -- Será SUCESSO",
    "When no status is specified, the API defaults to \"pending\". The `permit_create_task` policy allows this because the condition `!(context.input has status && context.input.status == \"completed\")` evaluates to true (no status field present).": "Sem indicar campos estranhos, a AWS vai gerar com default pending e o Cedar fará a liberação de rede orgânica com êxito.",
    "### Test 3: Update a task status to completed -- should SUCCEED": "### Teste 3: Atualizar uma tarefa legítima para concluída -- Será SUCESSO",
    "The `permit_update_task` policy permits all updates unconditionally, including setting status to \"completed\". The business rule only restricts *creation*, not updates.": "A modificação na API não possui restrição para a atualização. É validado com absoluto sucesso.",
    "## ENFORCE vs LOG_ONLY": "## Modo de Interação: ENFORCE vs LOG_ONLY",
    "| Mode | Behavior | Use case |": "| Modo | Comportamento da Malha | Cenário Principal AWS |",
    "| **ENFORCE** | Denies requests that violate policies. The agent receives an error. | Production — hard enforcement of business rules |": "| **ENFORCE** | Restrição Máxima Absoluta na rede, barreira total, falha e error. | Ambientes AWS Corporativos em Produção |",
    "| **LOG_ONLY** | Logs policy decisions but allows all requests through. | Testing — verify policies work before enforcing |": "| **LOG_ONLY** | O processo gera alertas em painel, mas as execuções furam a malha. | Teste Beta (Avaliação prévia antes da imposição total) |",
    "In LOG_ONLY mode, the \"create task with status completed\" request above would succeed, but the policy decision would be logged for review. This is useful when rolling out new policies — start with LOG_ONLY to monitor behavior, then switch to ENFORCE once you are confident.": "Uma excelente tática de implantação em produção. Inicie o sistema de monitoramento de regras da sua empresa em LOG_ONLY, observe quem está esbarrando nos bloqueios nos painéis de observabilidade e após calibragem da nuvem eleve a restrição total com ENFORCE.",
    "### Try it interactively": "### Conversando Interativamente na CLI",
    "Test the policy enforcement through the CLI chat. Try asking Aria to create a task that is already completed — the policy should block it:": "Abra seu terminal corporativo com a flag de JWT `--auth`. Envie comandos de fraude do sistema para ver a reação blindada da Aria:",
    "Try these prompts:": "Engenharia de prompts para o Teste prático:",
    "1. `Create a task called \"finish report\" with status completed` — should be denied": "1. `Crie a tarefa Terminar Relatório e já coloca o status como concluída` — O Motor deverá negar implacável a requisição.",
    "2. `Create a task called \"finish report\"` — should succeed (defaults to pending)": "2. `Crie a tarefa Terminar Relatório` — Irá passar nativamente (pendente).",
    "3. `Mark the finish report task as completed` — should succeed (updates are allowed)": "3. `Por favor, mude o status do Relatório para concluído` — O Update passará (é legal no escopo).",
    "## What's next": "## O que teremos no próximo lab?",
    "Cedar policies now govern Aria's behavior **deterministically** at the Gateway boundary. No matter what prompt injection or jailbreak is attempted, the policy engine will block requests that violate the business rules.": "Nosso modelo orgânico tem uma infraestrutura puramente blindada impenetrável por ataques de jailbreak de prompt. A camada de infraestrutura resolveu a restrição e governa a Aria.",
    "In **Module 7**, we add **observability and evaluations** -- OpenTelemetry tracing for monitoring and custom evaluators that score the agent's performance in production.": "No **Módulo 7**, implementaremos as camadas maduras do **Observability and Evaluations** -- Traces de monitoramento OTel (OpenTelemetry) para aferir e auditar todos os passos em produção, juntamente com a Inteligência LLM avaliando e dando notas sobre o comportamento global de produção corporativa da Aria."
}

def run():
    for f in glob.glob('*/notebook.ipynb', recursive=True):
        if '04-memory' in f or '05-gateway' in f or '06-policy' in f:
            with open(f, 'r', encoding='utf-8') as file:
                nb_data = json.load(file)
            
            modified = False
            for cell in nb_data.get('cells', []):
                if cell.get('cell_type') == 'markdown':
                    new_source = []
                    for line in cell.get('source', []):
                        new_line = line
                        for en_text, pt_text in mod04_06_translations.items():
                            if en_text in new_line:
                                new_line = new_line.replace(en_text, pt_text)
                                modified = True
                        new_source.append(new_line)
                    cell['source'] = new_source
                    
            if modified:
                with open(f, 'w', encoding='utf-8') as file:
                    json.dump(nb_data, file, indent=2, ensure_ascii=False)
                print(f"Translated {f}")

if __name__ == '__main__':
    run()
