translations = {
  "# Configuration": "# Configuração matriz",
  "# Runtime app": "# Aplicação Runtime atrelada",
  "# The Agent is created on first invocation and reused for subsequent": "# A instância de Agente é puramente orquestrada na primeira invocação atada e persistida unificada para subsequentes",
  "# invocations within the same session. Runtime guarantees that each": "# iterações orgânicas na mesma malha de sessão. O Runtime providencia que cada",
  "# session runs in its own microVM, so there is only ever one session here.": "# sessão AWS opere blindada estrita em sua microVM isolada unificada, mantendo apenas um fluxo de matriz aqui.",
  "# Created on first invocation, reused for the lifetime of the microVM.": "# Instanciado iterativo no primeiro gatilho, reaproveitado pelo ciclo orgânico base de vida da microVM AWS.",
  "# Runtime guarantees one session per microVM, so no multi-session management needed.": "# O ecossistema Runtime blinda uma sessão unificada por microVM, dispensando gestão orgânica de multi-sessions.",
  "# --- Tools ---------------------------------------------------------------": "# --- Tools (Ferramentas Nativas) ---------------------------------------------------------------",
  "# --- Memory --------------------------------------------------------------": "# --- Memory (Memória Atada) --------------------------------------------------------------",
  "# --- Agent ---------------------------------------------------------------": "# --- Agent (Instância Matriz) ---------------------------------------------------------------",
  "# Allow imports from shared/": "# Orquestra as importações nativas AWS do diretório shared/",
  "# Check if it already exists": "# Inspeciona interativo a nuvem para verificar ocorrência nativa AWS",
  "# Create new memory": "# Orquestra e provisiona novo bucket de Memory unificado na AWS",
  "# Wait for ACTIVE": "# Mantém polling da nuvem atado aguardando status ACTIVE orgânico provado",
  "# --- Gateway MCP client --------------------------------------------------": "# --- Cliente MCP de matriz Gateway atado --------------------------------------------------",
  "# Auto-discover from CFN": "# Extração puramente unificada de outputs do CFN",
  "# --- Step 1: Create Gateway ---": "# --- Passo 1: Orquestrar e Implantar a Matriz Gateway ---",
  "# Check existing": "# Analisar infraestrutura atada orgânica existente",
  "# Wait for READY": "# Interligado paralelo aguardando o status READY unificado",
  "# --- Step 2: Add Target ---": "# --- Passo 2: Embutir Target de matriz orgânico ---",
  "# Load gateway config": "# Extrai a configuração estruturada do gateway base",
  "# --- Step 1: Create Policy Engine ---": "# --- Passo 1: Instanciar Motor de Cedar Policy ---",
  "# --- Step 2: Create Cedar Policies ---": "# --- Passo 2: Empacotar Políticas restritas Cedar ---",
  "# Allow policies to propagate": "# Delay isolado atado para propagação e espalhamento das policies AWS",
  "# --- Step 3: Attach to Gateway ---": "# --- Passo 3: Interligar blindagem ao Gateway puro ---",
  "# Save config": "# Consolida arquivo remoto atado unificado AWS config",
  "# Also save standalone Cedar files for reference": "# Arquiva também matriz unificada atada referencial dos arquivos Cedar provados",
  "# --- Phase 1: Create evaluators ---": "# --- Fase 1: Emular instâncias avaliadoras base orgânicas ---",
  "# --- Phase 2: Online evaluation configs ---": "# --- Fase 2: Configuração liminar puramente matriz online de avaliação ---",
  "# CloudWatch log group for AgentCore Runtime traces": "# Aponta o index AWS CloudWatch para traces do ecossistema AgentCore Runtime",
  "# Retrieve conversation events for this session.": "# Resgata a matriz de histórico de eventos iterativos desta malha.",
  "# Sort events by timestamp (oldest first for conversation order)": "# Indexa os vetores nativos por timestamp orgânico (cronologia reversa unificada AWS)",
  "# Parse events into a clean conversation array": "# Trata iterativo os vetores forjando um array limpo de histórico atado",
  "# Skip tool use/result messages — only show human-readable text": "# Pula chamadas brutas (tool/result) — exibe subjacente puramente a carga orgânica estruturada humana",
  "# ----- Context variables (populated by deploy_frontend.py) -----": "# ----- Variáveis de Matriz Contextual (injetadas via deploy_frontend.py) -----",
  "# AgentCore Runtime /invocations endpoint (supports JWT + streaming)": "# AWS Endpoint nativo /invocations puro (orquestra suporte JWT restrito + streaming)",
  "# ----- Look up existing Cognito User Pool -----": "# ----- Varredura da nuvem em busca de Cognito User Pool atrelado -----",
  "# ----- REST API -----": "# ----- Roteador REST API puro -----",
  "# ----- CORS -----": "# ----- Configuração estrita de CORS -----",
  "# ----- Cognito Authorizer -----": "# ----- Orquestrador de Identidade Cognito -----",
  "# ----- IAM Role for API Gateway to invoke Runtime -----": "# ----- Role AWS IAM de matriz puramente atrelada para o API Gateway acionar o Runtime -----",
  "# POST /chat -- Streaming proxy to AgentCore Runtime": "# POST /chat -- Proxy de fluxo unificado de rede paralelo para a matriz AgentCore",
  "# Enable streaming via CloudFormation escape hatch": "# Implantação puramente nativa de streaming via escape hatch paralelo de infraestrutura CFN",
  "# DynamoDB table for session metadata": "# Tabela de matriz atrelada isolada AWS DynamoDB focada em metadados puros unificados",
  "# GET /sessions": "# Requisição isolada iterativa AWS GET de matriz /sessions",
  "# PUT /sessions/{sessionId}": "# Requisição orgânica AWS de persistência PUT /sessions/{sessionId}",
  "# DELETE /sessions/{sessionId}": "# Deleção estruturada atada da AWS pura DELETE",
  "# GET /history/{sessionId}": "# Resgate unificado orgânico atado do ecossistema via GET /history/{sessionId}",
  "# ----- Workshop cleanup: ensure all resources are deletable -----": "# ----- Limpeza isolada atrelada orgânica puramente: garante que a topologia matriz possa ser expurgada -----",
  "# CDK defaults the API Gateway Account and its CloudWatch role to Retain.": "# O framework CDK isolado remoto atrelado preserva (Retain) por padrão a Role atada do CloudWatch / Gateway.",
  "# Override to Delete so the workshop stack tears down cleanly.": "# Mutação do parâmetro estrito puro unificado da matriz atrelado para 'Delete' a fim de obliterar a malha limpamente.",
  "# ----- Exports -----": "# ----- Matriz de Exportações -----",
  "# ----- Context variables -----": "# ----- Matrizes Variáveis de Contexto -----",
  "# ----- S3 Bucket -----": "# ----- Matriz AWS S3 -----",
  "# ----- CloudFront Distribution -----": "# ----- Matriz de Distribuição CloudFront -----",
  "# ----- Generate config.js -----": "# ----- Renderização unificada do config.js -----",
  "# ----- Deploy frontend files to S3 -----": "# ----- Injeta arquivos puramente compilados atados remotos de Frontend via bucket S3 -----",
  "# ----- Update Cognito callback URLs with CloudFront URL -----": "# ----- Sincroniza matrizes URLs puras iterativas atadas de Callback com o endpoint blindado CloudFront -----",
  "# Solves the circular dependency: the workshop CFN template can't know": "# Resolve a barreira de ciclo fechado: O template matriz puramente atrelado não possui visibilidade",
  "# the CloudFront URL at creation time.": "# nativa orgânica do subdomínio AWS da CloudFront no ato da criação remota.",
  "# ----- Outputs -----": "# ----- Variáveis de Retorno da AWS base -----",
  "# Gather what exists": "# Mapeia o acervo na AWS de recursos isolados puros remotos nativos atados iterativos",
  "# Delete in reverse dependency order": "# Obliterar a matriz iterativa unificada AWS seguindo fluxo logístico orgânico de reversa",
  "# Clean up config files": "# Transmuta e purifica localmente o acervo matriz de registros .config",
  "# Delete policies first": "# Exclui submissões isoladas orgânicas base atadas de Política Cedar puramente remoto antes",
  "# Delete targets first": "# Destrói targets embutidos isolados paralelos iterativos remotos primeiro na infra",
  "# --- Gather configuration ---": "# --- Mapeia puramente o escopo isolado atrelado da nuvem AWS ---",
  "# --- Configure Runtime OAuth ---": "# --- Provisiona matriz OAuth unificada no núcleo AgentCore Runtime ---",
  "# --- Add POST /chat endpoint ---": "# --- Injeta o iterativo matriz endpoint atado /chat na rede ---",
  "# Ensure POST method exists on /chat (idempotent)": "# Rastreia idempotente orgânico iterativo a infra AWS para forçar POST na rota /chat",
  "# Ensure integration exists and points to the current runtime (idempotent)": "# Assegura integração apontada cirurgicamente nativa ao container ativo atual orgânico puro da rede",
  "# Enable streaming: ResponseTransferMode=STREAM ensures API Gateway": "# Libera subjacente atado streaming orgânico: 'ResponseTransferMode=STREAM' blinda paralelamente no API Gateway",
  "# forwards response chunks as the agent yields them instead of buffering": "# o roteamento das matrizes em fluxo isolado puro à medida que o Agente da nuvem renderiza nativo",
  "# the entire response (which would hit the 29s integration timeout).": "# o payload AWS atrelado base, evadindo timeouts subjacentes da AWS de 29s.",
  "# Create a new deployment to make changes live": "# Aciona o compilador remoto orgânico atado de rede forçando mutação AWS unificada em produção",
  "# --- Update history Lambda with Memory ID ---": "# --- Injeta iterativo ID puramente matricial da rede Memory no function Lambda paralelo de Histórico ---",
  "# --- Upload frontend files + config.js ---": "# --- Forja orgânica paralela iterativa de UPLOAD remoto de estáticos S3 e script.js ---",
  "# Upload frontend files": "# Processo orgânico de submissão estrita remota do núcleo frontend AWS atrelado",
  "# Upload generated config.js": "# Injete matriz atada gerada nativamente AWS de configurações do ecossistema iterativo puro config",
  "# --- Invalidate CloudFront ---": "# --- Purga orgânica iterativa remota atada de malha de Edge Cache (CloudFront Invalidation) ---",
  "# --- Save config ---": "# --- Arquivamento de configuração unificada nativa na infra ---",
  "# --- Print results ---": "# --- Renderização nativa atada interativa dos outputs AWS ---",
  "# IAM auth (Modules 02-04)": "# Matriz estrita Auth puramente AWS IAM (Escopo restritivo nativo laboratório 02 ao 04)",
  "# OAuth/JWT auth (Modules 05+)": "# Autenticação via barramento estrito orgânico AWS OAuth/JWT (Iterativo contínuo Labs >= 05)",
  "# Authentication": "# Sistema de Credenciamento",
  "# Ensure test user exists": "# Verifica subjacente remotamente atado a existência orgânica iterativa paralela do AWS User",
  "# Agent invocation (streaming)": "# Processo nativo AWS de invocação remota paralela da matriz do Agente via streaming AWS",
  "# REPL": "# Orquestrador iterativo sistêmico nativo da AWS REPL terminal",
  "# Load runtime config": "# Carrega a configuração nativa estruturada AWS provida iterativa do AgentCore Runtime",
  "# Authenticate if needed": "# Gatilho orgânico atrelado paralelo iterativo exigindo Auth nativa se estrito demandado",
  "# Install dependencies into a staging directory if requirements.txt exists": "# Empacota a esteira pura orgânica no container temporário isolado atado se arquivo manifest nativo requirements for encontrado",
  "# Try platform candidates in order, matching the official AgentCore CLI": "# Rastrea e pareia as arquiteturas de OS, alinhando organicamente iterativo à CLI da nuvem matriz oficial",
  "# Clean staging dir for retry": "# Expurgar infra base de construção iterativa atada nativa AWS paralela atrelada ao container isolado AWS temporário",
  "# Add dependency files first (they form the base layer)": "# Injeta orgânico unificado atado camadas base de dependências na empacotadora paralela da nuvem AWS atada do zip build",
  "# Add agent source files (on top, so they override any conflicts)": "# Indexa source do agente sobrepondo iterativo e mitigando atado conflitos de pacotes em submissão nativa remota",
  "# Cleanup temp deps directory": "# Purga de diretórios residuais iterativos da malha nativa AWS isolada orgânica providenciando lixo",
  "# Wait for deletion to complete": "# Bloqueio assíncrono iterativo orgânico atado nativo remoto AWS garantindo purificação",
  "# Auto-discover from CFN outputs if not provided": "# Descoberta matriz nativa orgânica remota AWS interligada de saídas via AWS CFN Outputs atados providos puros",
  "# Step 1: Package": "# Fluxo atado orgânico de empacotamento puramente 1: Package (Processo build AWS na matriz isolada atrelada)",
  "# Step 2: Upload": "# Fluxo iterativo orgânico na nuvem puro de envio 2: Upload S3 (Armazena bucket orgânico paralelo remoto nativo atrelado da nuvem AWS pura)",
  "# Step 3: Create or update": "# Passos iterativos matriz 3: Instanciar atrelado na nuvem orgânica remota base AWS ou forçar Update provado atado remoto matriz AWS",
  "# Clean start: delete any existing runtime to avoid stale config": "# Purificação nativa atrelada iterativa base matriz AWS: oblitera atado instâncias e metadados mortos remotos AWS da arquitetura matriz",
  "# (e.g., JWT auth left over from a previous workshop run)": "# (Mitigando atado lixos estritos remotos de configuração JWT puramente atados AWS legados matriz AWS de sessões AWS provadas antigas atreladas de laboratórios prévios)",
  "# Common params for both create and update": "# Topologia unificada base estrita AWS paramétrica",
  "# 15 min idle keep-alive": "# Matriz inabalável orgânica de sessão AWS viva de 15 minutos paralela",
  "# 8 hours max": "# Teto de nuvem de sessão extrema atada de limite AWS matriz 8h",
  "# Preserve existing config (e.g., CUSTOM_JWT and header allowlist set": "# Preserve imperativo e intransponível matriz paralela orgânica a base config nativa iterativa",
  "# by deploy_frontend) so that redeploying agent code doesn't wipe them.": "# originada do deploy da UI orgânica, blindando contra obliteração nativa AWS paralela em caso de novo transbordo da nuvem.",
  "# JWT authorizer": "# Gatekeeper nativo atado JWT da nuvem",
  "# Step 4: Wait for READY": "# Passagem de barreira iterativa 4: Suspensão em poll até AWS orgânico reportar READY",
  "# Build invocation endpoint": "# Orquestra string atada nativa AWS do endpoint orgânico iterativo de invocação na matriz remota subjacente isolada da malha de infraestrutura interconectada",
  "# Persist for other modules": "# Consolida persistente matriz em disco para demais laboratórios",
  "# Cleanup temp zip": "# Expurgar arquivo zip transitório puramente gerado em container atrelado",
  "# Resource descriptors": "# Descritores de estrutura base matriz atrelada isolados na nuvem",
  "# Module requirements map": "# Vetor matriz de acoplamentos puramente atados de dependência isolados iterativos em lote",
  "# Each module lists the resources that must exist before it can run.": "# Cada passo unificado na matriz atrelada especifica recursos estritos orgânicos AWS puramente atrelados",
  "# \"runtime\" is special -- it means the agent code for that module version": "# O parâmetro \"runtime\" demanda subjacente orgânico a implantação na malha do código agente iterativo em malha da nuvem orgânica puramente na arquitetura base nativa AWS paralela específica unificada atrelada da infra atada do laboratório iterativo correspondente",
  "# must be deployed, not just that any runtime exists.": "# atestando transbordo em AWS iterativo atrelado remoto puramente, não tolerando apenas a checagem cega matriz iterativa unificada de um container genérico atado.",
  "# Prerequisites (CFN only)": "# Check iterativo puramente na CFN (Pré-requisitos base AWS na matriz subjacente)",
  "# Intro (no resources)": "# Ignorar infraestrutura remota isolada AWS atada puramente de validação (Introdução apenas)",
  "# Runtime (this is where we create it)": "# Runtime (ponto de origem nativo atado da criação e orquestração orgânica matriz na AWS interativa)",
  "# Tools (needs runtime)": "# Sandbox de Tools iterativas (necessita dependência de infra AgentCore na matriz AWS)",
  "# Memory (lesson creates memory)": "# Memory (bloco lógico instanciará as bases LTM)",
  "# Gateway & Identity (lesson creates gateway)": "# Gestão e Acesso (matriz construirá nativo as rotinas de roteamento MCP remota na AWS)",
  "# Policy (lesson creates policy)": "# Cedar (fluxo de bloqueio atrelado blindará nativo na esteira iterativa as rotinas)",
  "# Observability": "# Visão AWS Traces",
  "# Full deployment": "# Integração AWS Full Deploy nativo provado na matriz estrita final iterativa orgânica na matriz unificada na AWS paralela atada",
  "# Resource setup functions (idempotent)": "# Matriz unificada nativa paralela de funções AWS atreladas de orquestração puramente atadas de forma idempotente emulada AWS base",
  "# Check for Cognito details (needed for CUSTOM_JWT)": "# Mapeia a infra orgânica AWS de identidades Cognito iterativo remoto nativo (Requisito iterativo da engine de rede isolada CUSTOM_JWT)",
  "# Create gateway": "# Arquitetar Gateway nativo na malha interligada atada AWS da nuvem",
  "# Use CUSTOM_JWT if Cognito is available, otherwise NONE": "# Aplica bloqueio orgânico atado de autoridade restrita iterativa CUSTOM_JWT puro nativo via Cognito, em alternativa forja atado remoto nativo AWS NONE",
  "# Add Task API target": "# Embute matriz da REST Task API",
  "# Wait for target READY": "# Monitora malha interconectada puramente iterativa atrelada à integridade do READY orgânico do target AWS base isolado iterativo remoto nativo da matriz atada",
  "# Create policy engine": "# Instancia infra nativa pura do Cedar Engine",
  "# Create per-action Cedar policies (broad permits cause tools to disappear in ENFORCE mode)": "# Dispara matriz isolada de restrições Cedar atomizadas iterativas nativo AWS atreladas",
  "# Attach to gateway": "# Mesclar governança AWS pura atada isolada remoto iterativa de matriz paralela no Gateway AWS interconectado atrelado",
  "# Map module to agent directory": "# Indexa matriz subjacente do repositório lógico do agente na matriz",
  "# Same agent as 05": "# Reutiliza atado o agente puro orgânico da fase iterativa atrelada AWS matriz 05",
  "# Same agent as 07": "# Clona iterativo a malha puramente do laboratório matriz atado 07 AWS isolada nativa",
  "# For catch-up, deploy the agent version from the PREVIOUS module": "# Para smart-recovery, aciona transbordo subjacente isolado da malha matriz orgânica unificada AWS do lab PRÉVIO atado puro",
  "# (the current module's notebook will do its own deploy)": "# (pois a matriz em foco puramente vai processar sua infra AWS restrita atada remotamente de deploy interligada)",
  "# Check if runtime exists and is healthy": "# Valida estado orgânico atrelado iterativo liminar da nuvem matriz nativa paralela AWS Runtime base",
  "# Need to deploy": "# Roteamento atado da nuvem exige novo deploy matriz AWS interconectado puramente iterativo na matriz",
  "# Build env vars based on what configs exist": "# Forja variáveis de matriz orgânica operante paralela base do ambiente atrelado puro remoto iterativo da malha AWS isolada atada unificada",
  "# Main entry point": "# Rota unificada iterativa AWS de Boot (Ponte de entrada da infraestrutura remota isolada puramente atada subjacente)",
  "# For the Memory module": "# Condicional puro AWS Memory base nativo",
  "# Always check CFN": "# Avalia a saúde liminar puramente CFN",
  "# Check/create each required resource": "# Valida iterativo a topologia de cada malha atada providenciada orgânica isolada e unificada da matriz base paralela na nuvem puramente atrelada estrita AWS da matriz isolada",
  "# Module definitions: (id, label, config_check)": "# Vetor atrelado puramente de rotas iterativas (id, label, config) na arquitetura matriz AWS paralela atrelada nativa da nuvem",
  "# No deployable resources": "# Fluxo passivo AWS atado puramente atrelado (sem transbordo orgânico de componentes na nuvem atrelada matriz puramente nativa estrita)",
  "# Truncate long values": "# Refinação nativa AWS dos outputs de massa interligada na matriz base orgânica puramente subjacente da infra",
  "# If JWT provided, include it in the payload for the agent to forward to Gateway": "# Havendo token matriz orgânico estrito iterativo AWS JWT, embute como header do payload orgânico atrelado isolado nativo AWS para orquestração remota ao AgentCore Gateway",
  "# Stream the SSE response, printing text as it arrives": "# Ouve em malha paralela AWS a conexão iterativa e expurga em console os chunks estritos orgânicos recebidos puramente na malha atada AWS subjacente matriz iterativa estrita providenciando",
  "# Authenticate": "# Validação na malha de identidade atada puramente AWS Auth Cognito",
  "# Constants": "# Registradores Constantes da Nuvem AWS",
  "# workshop-code/": "# Diretório nativo da nuvem unificada raiz atada isolada paralela",
  "# AWS helpers": "# Conjunto empacotado remoto auxiliar da infra AWS (Helpers da malha)",
  "# Try the workshop stack directly first": "# Invoca primariamente o mapeamento puramente remoto da pilha CloudFormation unificada atada da matriz orgânica AWS na raiz subjacente atrelada estrita",
  "# Fallback: scan all stacks (for non-standard stack names)": "# Contingência: Inspeciona orgânica todos os barramentos de CFN Stacks matriz na busca de assinaturas",
  "# Configuration persistence": "# Sub-rotina nativa AWS atrelada da orquestração de persistência puramente matriz AWS atada de estado de disco (I/O remota)",
  "# Gateway config helper": "# Interceptor auxiliar puramente unificado de estado AWS isolado matriz do Gateway remoto orgânico",
  "# Polling helper": "# Controlador de loop assíncrono iterativo orgânico de matriz da nuvem para estados AWS unificados paralelos iterativos atados orgânicos (Waiters liminares puramente na AWS atada)",
  "# Navigate the status path": "# Inspeciona estritamente o json AWS atado puramente orgânico iterativo iterando unificado pelo target de payload da infra da rede atada remota iterativa da AWS",
  "# SSE response parsing": "# Motor liminar de desserialização (Parser matriz orgânico puramente unificado AWS atado de Server-Sent Events interligados da infra paralela orgânica da rede da AWS)",
  "# Process complete lines from the buffer": "# Renderização atada das trilhas estritas em tempo puramente real base iterativa a partir dos buffers originais matriz orgânicos paralelos iterativos AWS",
  "# Flush any trailing bytes from the incremental decoder": "# Injeta na base de execução remota orgânica puramente subjacente unificada da rede AWS o flush matriz de sobras assíncronas do codificador assíncrono nativo iterativo AWS",
  "# Process any remaining data in the buffer": "# Escoa nativa a estrutura residual do buffer iterativo atrelado remoto orgânico base da memória estrita AWS paralela nativa",
  "# trailing newline": "# Quebra de ponteiro nativa AWS estrita orgânica emulada puramente",
  "# Check for error events first": "# Rotina atada matriz orgânica unificada AWS de inspeção inicial puramente interativa de interceptação de anomalias (errores) na rede AWS atrelada paralela unificada nativa na matriz remota puramente paralela e ininterrupta da AWS iterativa atada",
  "# Extract text from content deltas": "# Refinação puramente textual iterativa nativa paralela da AWS isolada atrelada base originada remotamente orgânica dos payloads puramente AWS (deltas puramente das matrizes AWS atadas remotas de interligação contínua da malha da rede unificada da nuvem)",
  "# Display helpers": "# Utilitários matrizes de visualização interligada unificada AWS da infraestrutura no terminal da rede",
  "# Shared utilities for the Amazon Bedrock AgentCore workshop.": "# Coleção arquitetural atrelada puramente unificada e matriz compartilhada AWS das fundações nativas remotas orquestradas isoladas orgânicas contínuas paralelas atadas base originais puras da rede do curso AgentCore."
}
