import json
import glob

mod07_99_translations = {
    # MODULE 07
    "# Module 7: Observability & Evaluations -- Monitoring in Production": "# Módulo 7: Observabilidade e Avaliações -- Monitoramento em Produção",
    "Throughout this workshop, you have been enabling **Tracing** on each AgentCore resource as it was created. The Runtime has been exporting OpenTelemetry traces since Module 2, and Memory and Gateway resources have had tracing enabled since Modules 4 and 5.": "Ao longo deste laboratório, você tem habilitado o **Tracing** em cada recurso do AgentCore. O Runtime exporta os traces OpenTelemetry desde o Módulo 2, e os recursos de Memória e Gateway tiveram a telemetria ativada nos Módulos 4 e 5.",
    "In this module, you explore that accumulated data, deploy the final production-hardened version of Aria (V5), then set up **custom evaluators** that continuously score the agent's performance.": "Neste módulo, faremos a exploração desses dados de telemetria acumulados, a implantação da versão final robusta da Aria (V5) e a configuração de **avaliadores customizados (custom evaluators)** que monitorarão o desempenho do agente de forma contínua.",
    "## What you will learn": "## Objetivos do Laboratório",
    "- **Exploring traces**: Navigate the CloudWatch GenAI Observability dashboard to view agent traces, memory operations, and gateway requests": "- **Exploração de rastros**: Navegar pelo painel de observabilidade GenAI do CloudWatch para auditar as inferências, operações de memória e requests no Gateway.",
    "- **Understanding the trace pipeline**: How ADOT instrumentation and X-Ray Transaction Search work together": "- **Arquitetura de telemetria**: Como a instrumentação via ADOT e a indexação do X-Ray Transaction Search operam no pipeline.",
    "- **Custom evaluators**: LLM-as-judge evaluators that score response quality and tool usage": "- **Avaliadores Customizados**: Avaliações do tipo LLM-as-judge para auditar a qualidade das respostas e o rigor no uso das ferramentas MCP.",
    "- **Online evaluations**: Continuous monitoring with configurable sampling rates": "- **Avaliações contínuas (Online evaluations)**: Monitoramento proativo com taxas de amostragem configuráveis no fluxo de log.",
    "Ensure all prerequisites from earlier modules are in place.": "Certifica a integridade da stack construída nos módulos anteriores.",
    "## How observability has been working behind the scenes": "## Arquitetura de Observabilidade (Background)",
    "Every deploy and resource creation in this workshop has included observability configuration. Here's what was set up:": "Todo deploy corporativo deste laboratório foi orquestrado em conjunto com o pipeline de tracing. O fluxo configurado foi:",
    "### Agent tracing (Modules 2-6)": "### Tracing do Agente",
    "Every time you deployed Aria, the deployment helper:": "Em todo deploy automático efetuado pelo script auxiliar:",
    "1. Included `aws-opentelemetry-distro` in the agent package": "1. Inclusão da biblioteca nativa `aws-opentelemetry-distro` na imagem Docker.",
    "2. Wrapped the entrypoint with `opentelemetry-instrument` to auto-instrument HTTP calls, LLM invocations, and tool calls": "2. Empacotamento do entrypoint corporativo via `opentelemetry-instrument`, instrumentando nativamente as chamadas HTTP, acesso aos FMs (LLMs) e rotinas das ferramentas MCP.",
    "3. Set `tracingConfiguration={\"enabled\": True}` on the Runtime": "3. Execução da API `tracingConfiguration={\"enabled\": True}` injetada no AgentCore Runtime.",
    "This means every agent invocation you've run -- from simple conversations in Module 2 to policy-enforced Gateway calls in Module 6 -- has been producing trace data.": "Esse nível profundo de instrumentação significa que todas as interações executadas desde o Módulo 2 geraram logs estruturados para a AWS.",
    "### Resource-level tracing (Modules 4-5)": "### Tracing de Infraestrutura (Nível de Recurso AWS)",
    "In Modules 4 and 5, you enabled **Tracing** on the Memory and Gateway resources through the AgentCore console. This populates the **Memory** and **Gateways** tabs in the AgentCore Observability dashboard with detailed spans for each operation.": "Nos Módulos 4 e 5 a habilitação na console acoplou os serviços internos. Isso preencheu nativamente os painéis da AWS com eventos complexos em árvore para cada etapa de recuperação.",
    "### Service-vended metrics (automatic)": "### Métricas geradas pelas APIs AWS",
    "AgentCore automatically emits CloudWatch metrics for every resource -- invocations, latency, errors, throttles, CPU/memory usage. These appear with **zero configuration** in the `Bedrock-AgentCore` namespace.": "A Amazon Bedrock emite sinais sem necessidade de configuração ativa — como latência, instabilidade, erros de throttle ou restrição de hardware (CPU/RAM). Tudo acessível com **zero configuração** via CloudWatch (namespace `Bedrock-AgentCore`).",
    "### Trace flow": "### Arquitetura do Fluxo de Telemetria",
    "## Explore existing traces": "## Análise Forense dos Logs (Tracing)",
    "You already have trace data in CloudWatch from every agent invocation across Modules 2-6. Let's also generate a few more targeted prompts that exercise different capabilities, then explore everything in the dashboard.": "Métricas brutas geradas nas iterações anteriores estão consolidadas no Amazon CloudWatch. Vamos exercitar queries mais complexas forçando a inferência, para validar os nós no painel visual.",
    "## Viewing traces in CloudWatch": "## Acessando o CloudWatch da AWS",
    "Open the **CloudWatch Console** and navigate to **Application Signals** > **GenAI Observability** > **Bedrock AgentCore**. You'll see tabs for each resource type:": "No console de gerenciamento, abra o **CloudWatch Console**. Navegue na lateral esquerda até **Sinais de Aplicação (Application Signals)** > **GenAI Observabilidade** > **Bedrock AgentCore**. Analise:",
    "### Agents tab": "### Aba de Agentes",
    "Shows all agent invocations with trace details. Click any trace to see the full waterfall:": "Contém as invocações totais. Ao expandir o log, a estrutura em 'Waterfall' exibe:",
    "- **Root span**: The full invocation (request to response)": "- **Root span**: O nó raiz de requisição HTTP",
    "- **LLM spans**: Each call to the foundation model (with token counts and latency)": "- **LLM spans**: Chamadas de rede para a Modelagem Básica (FM), listando os tokens gastos por payload e a latência de geração",
    "- **Tool spans**: Each tool invocation (code interpreter, browser, Gateway tools)": "- **Tool spans**: Invocações seguras nas ferramentas restritas do ecossistema AgentCore",
    "- **Memory spans**: Retrieval and storage operations": "- **Memory spans**: Buscas de vetor semântico na infra do DynamoDB",
    "- **Gateway spans**: MCP requests to the Gateway (including policy evaluation results)": "- **Gateway spans**: Passagem do token JWT para interceptação no Cedar e autorização no Target API",
    "### Memory tab": "### Aba da Memória",
    "Shows Memory resource metrics and (with tracing enabled) detailed spans for:": "Disseca as rotinas em profundidade técnica:",
    "- `CreateEvent`, `RetrieveMemoryRecords`, `ListMemoryRecords`": "- `CreateEvent`, `RetrieveMemoryRecords`, `ListMemoryRecords` (Comandos da API CRUD)",
    "- Extraction processing (new memory formation from events)": "- Indexação de dados abstratos",
    "- Consolidation processing (merging with existing memories)": "- Merging e mesclagem heurística da inferência consolidada",
    "### Built-in Tools tab": "### Aba das Ferramentas Nativas AWS",
    "Shows Code Interpreter and Browser metrics:": "Dados das instâncias rodando o Browser headless e a sandbox Python:",
    "- Invocation counts, latency, errors": "- Contador de logs e taxas de falhas na sandbox",
    "- CPU and memory usage per tool session": "- Telemetria de CPU/RAM de cada microVM isolada",
    "### Gateways tab": "### Aba do Gateway",
    "Shows Gateway metrics and spans for:": "Escrutínio do ambiente Gateway e regras de negócio:",
    "- `List Tools`, `Call Tool`, `Search Tools` operations": "- As rotinas padrão do SDK: `List Tools`, `Call Tool`",
    "- Policy evaluation results (allow/deny decisions, determining policies)": "- Registros determinísticos gerados pelo Policy Engine (O motivo de um ALLOW ou DENY do Cedar)",
    "- Target execution time (how long the backend API took)": "- Latência da infraestrutura externa (backend)",
    "### Other views": "### Visões Operacionais Avançadas",
    "- **X-Ray traces** > **Service map**: Visualize the dependency graph between Runtime, LLM, tools, Memory, and Gateway": "- O **Mapa de Serviços (Service Map) do AWS X-Ray**: Mostra a topologia em grafos da arquitetura em runtime real.",
    "- **CloudWatch Logs Insights**: Query structured trace data": "- O **Log Insights**: Para varredura usando o motor SQL-like de parsing JSON.",
    "> **Tip:** You should see traces spanning the entire workshop -- from simple Module 2 conversations through to the policy-enforced Gateway calls in Module 6. The richer your earlier exploration, the more data you have here.": "> **Boas Práticas AWS:** Recomenda-se analisar a variação da telemetria desde o Módulo 2 e comparar com as restrições adicionadas no módulo do IAM e Gateway.",
    "## Custom Evaluators": "## Avaliações Computacionais (Custom Evaluators)",
    "Observability tells you *what* the agent did. **Evaluations** tell you *how well* it did.": "A Observabilidade lhe diz *o que* ocorreu em rede. **Avaliações (Evaluations)** dizem com *que grau de eficiência corporativa* a arquitetura atuou.",
    "An evaluator is an LLM-as-judge that scores your agent's behavior. You define:": "O Avaliador funciona delegando o crivo a outra LLM via AWS que irá auditar cegamente as instâncias. Você define os seguintes parâmetros:",
    "- **Rating scale** (e.g., 1-5)": "- **Escala de Precisão (Rating scale)** (Ex: 1 a 5).",
    "- **Instructions** -- a rubric the judge follows": "- **Rubricas de Inspeção** -- As regras exatas que a AWS forçará o juiz a ler.",
    "- **Evaluation level** -- SESSION (whole conversation) or TRACE (individual turn)": "- **Escopo da Avaliação** -- Uma auditoria GLOBAL (Sessão completa) ou uma restrita ao TRACE do loop lógico.",
    "| Concept | Description |": "| Construto de Nuvem | Descrição Arquitetural |",
    "| **Evaluator** | A custom rubric that defines how to score agent behavior |": "| **Avaliador (Evaluator)** | Classe que modela o padrão LLM-as-judge para validar respostas. |",
    "| **Evaluation level** | **SESSION** evaluates the full conversation. **TRACE** evaluates individual tool calls |": "| **Evaluation level** | O `SESSION` audita o log inteiro de chat. O `TRACE` foca na decisão atômica da ferramenta MCP. |",
    "| **Online evaluation** | An evaluator attached to a live agent with a sampling rate |": "| **Avaliação Online** | Avaliação executada de forma nativa e assíncrona nas requisições reais. |",
    "| **Sampling rate** | Percentage of invocations to evaluate (e.g., 10%). Controls cost and coverage |": "| **Taxa de Amostragem** | % do tráfego desviado pela AWS para ser avaliado. Mitiga custos abusivos em produção. |",
    "### Create Evaluator 1: ResponseQuality (SESSION level)": "### Modelagem de Avaliador 1: Qualidade Global de Sessão (SESSION)",
    "This evaluator examines the full conversation session and scores on a 1-5 scale. We use the **control plane** client (`bedrock-agentcore-control`) to create evaluators.": "Este avaliador será encarregado de classificar a sessão macro no limite 1 a 5. Invocamos a rede interna via `bedrock-agentcore-control`.",
    "The evaluator config uses the `llmAsAJudge` structure with:": "A configuração embarca as seguintes instruções da classe `llmAsAJudge`:",
    "- **Instructions** containing placeholders that get filled with trace data": "- **Instruções** repletas de marcações de string dinâmicas (placeholders).",
    "- **Rating scale** with numerical values, labels, and definitions": "- **Range de Medição** amparada por rótulos restritos e descritivos.",
    "- **Model config** specifying which foundation model acts as the judge": "- **Model Config** alocando o id da fundation model que agirá como Auditor.",
    "### Create Evaluator 2: ToolUsage (TRACE level)": "### Modelagem de Avaliador 2: Uso Profundo de Ferramenta (TRACE)",
    "This evaluator examines individual tool calls within a trace and scores whether the agent selected the right tools and used them efficiently.": "O Auditor focará inteiramente na eficácia granular da adoção do endpoint. O agente atendeu perfeitamente ao MCP ou desperdiçou a API?",
    "## Set up online evaluation": "## Deployment da Avaliação Assíncrona Online",
    "Online evaluations attach evaluators to a live agent with a **sampling rate**. They run asynchronously -- they do not slow down the agent's responses.": "Evaluations inseridos no modo *Online* agem lendo assincronamente (background data lake) o log e, portanto, **não injetam latência ao usuário final**.",
    "Online evaluations require:": "Esteira de dependências para deploy:",
    "- A **data source** pointing to the CloudWatch log group that contains the agent's OTel trace data": "- Uma base de dados log-in apontada ao CloudWatch onde o OTel faz dump dos traces.",
    "- An **execution role** with permissions to read logs and invoke Bedrock models": "- Uma Role IAM com grant pleno de leitura do LogGroup e privilégios de invocação ao modelo.",
    "- **Evaluator references** -- either built-in or custom evaluators": "- Os IDs remotos criados na AWS.",
    "AgentCore provides several built-in evaluators:": "Para acelerar os testes, a própria AWS possui classes predefinidas (built-in):",
    "| Evaluator | Level | What it measures |": "| Id da Classe AWS | Level | Monitoramento Auditado |",
    "| `Builtin.Helpfulness` | TRACE | How helpful the agent's responses are |": "| `Builtin.Helpfulness` | TRACE | Nível de ajuda provido ao usuário final. |",
    "| `Builtin.GoalSuccessRate` | SESSION | Whether the agent achieved the user's goal |": "| `Builtin.GoalSuccessRate` | SESSION | Avaliação técnica da conclusão efetiva do problema raiz. |",
    "| `Builtin.Correctness` | TRACE | Factual accuracy of responses |": "| `Builtin.Correctness` | TRACE | Integridade factual (detecção formal de alucinações de dados). |",
    "| `Builtin.Conciseness` | TRACE | Whether responses are appropriately concise |": "| `Builtin.Conciseness` | TRACE | Bloqueio de respostas prolixas (excesso desnecessário de output). |",
    "| `Builtin.ToolSelectionAccuracy` | TOOL_CALL | Whether the agent chose the right tools |": "| `Builtin.ToolSelectionAccuracy` | TOOL_CALL | Acuidade formal ao escolher a ferramenta da REST API. |",
    "Below we use the `create_online_evaluation_config` control-plane API to wire up two built-in evaluators to Aria's trace log group. We set the sampling rate to 100% so that evaluation results appear quickly during the workshop. In production, you would typically use a lower rate (e.g., 10%) to control cost.": "As invocações abertas usarão a classe `create_online_evaluation_config`. No laboratório operaremos em **100% de sampling (amostragem)**, embora em produção corporativa a recomendação estrita seja atenuar para **10%** por questões de governança de faturamento AWS.",
    "### Save configuration": "### Salvar manifesto localmente",
    "## Run on-demand evaluation with custom evaluators": "## Processamento Batch / On-Demand das Avaliações",
    "The custom evaluators we created (ResponseQuality and ToolUsage) are not wired to online evaluation -- they are designed for **on-demand** use. On-demand evaluation lets you score a specific session by:": "Você pode auditar o log que você quiser disparando instâncias customizadas via **On-demand execution**. Ideal para processamento em lotes noturnos em data lakes corporativos.",
    "1. **Downloading span logs** from CloudWatch for a given session ID": "1. Fazendo uma querie de ingestão via SDK do CloudWatch e baixando o payload bruto do sessionID.",
    "2. **Calling the `evaluate()` API** on the data plane with those spans": "2. Injetando esse binário massivo no método restrito `evaluate()` em data-plane AWS.",
    "This is useful for debugging specific conversations, testing evaluator rubrics, and investigating quality issues.": "Um fluxo perfeito para engenheiros MLOps validarem regressões nas LLMs e debugar tickets de suporte críticos do negócio.",
    "### Step 1: Invoke the agent and capture the session ID": "### Processo 1: Gerar as transações do rastreio",
    "We need a session ID from a recent invocation. Let's run one now and save it.": "Capturar na memória de script um SessionID corporativo.",
    "### Step 2: Download span logs from CloudWatch": "### Processo 2: Query CloudWatch e parse do dump log",
    "The `evaluate()` API requires the raw span logs as input. We query CloudWatch Logs Insights to download all spans for the session.": "É obrigatório injetar um blob RAW com o log nativo AWS no `evaluate()`. Usaremos a sintaxe de CloudWatch Logs Insights.",
    "> **Note:** It can take 1--2 minutes for spans to appear in CloudWatch after an invocation. If the query returns empty results, wait and re-run this cell.": "> **Importante:** A AWS adota garantias de eventual consistência. O atraso no dump dos logs varia de 1 a 2 minutos no cluster do CloudWatch. Caso falhe de imediato, rode as células em repetição.",
    "### Step 3: Run the custom evaluators": "### Processo 3: Orquestração Batch",
    "Now we call the `evaluate()` **data plane** API with each custom evaluator. The API sends the span data to the LLM judge, which scores the session according to our rubric.": "Iremos realizar o upload via POST usando `evaluate()` na infraestrutura de processamento da Bedrock. A rubrica será analisada contra o contexto e devolvida com pontuação e relatório.",
    "- **ResponseQuality** (SESSION level) — evaluates the entire conversation": "- A classe **ResponseQuality** validará a transação do ID inteira.",
    "- **ToolUsage** (TRACE level) — evaluates each individual turn where tools were used": "- A classe **ToolUsage** escrutinará minuciosamente as saídas da ferramenta interna.",
    "### How on-demand evaluation works": "### Pipeline Operacional e Análise Crítica do Avaliador",
    "The flow you just ran:": "Revisão arquitetural dos microserviços AWS em ação:",
    "1. **Invoked the agent** — this generated OpenTelemetry spans that were written to CloudWatch Logs": "1. Ação `invoke`: A Aria processou. A OpenTelemetry enxertou Spans na VPC que foram transmitidos assincronamente ao CloudWatch.",
    "2. **Downloaded spans** — queried CloudWatch Logs Insights for all spans matching the session ID, from both the Runtime log group and the `aws/spans` log group": "2. Download via Boto3 (Query). A requisição SQL-like uniu os dumps nos diretórios AWS associados ao Session ID isolado.",
    "3. **Called `evaluate()`** — passed the raw span data to the data plane API along with the evaluator ID. The service extracted the relevant context from the spans, filled in the evaluator's template placeholders, and sent everything to the judge model": "3. Passagem de bastão: `evaluate()`. Os arrays da telemetria RAW subiram no servidor. A AWS converteu o JSON, gerou o template e montou dinamicamente as variáveis de string da prompt do Avaliador.",
    "4. **Received scores** — the LLM judge returned a numerical score, label, and explanation for each evaluation target (one result for SESSION-level, one per trace for TRACE-level)": "4. Resultados: Retorno síncrono com a nota calculada, log explícito e motivo detalhado para justificar os passos das métricas da auditoria.",
    "On-demand evaluation is ideal for:": "Recomendamos que ambientes de nuvem maduros usem esse formato para:",
    "- **Testing evaluator rubrics** before deploying them as online evaluations": "- Iterações de ajuste nas rubricas limitadas a ambientes restritos (Test).",
    "- **Investigating specific sessions** that received low online evaluation scores": "- Fazer o drill-down manual de métricas baixas coletadas nos painéis online.",
    "- **Comparing evaluator versions** side by side on the same session data": "- Teste A/B rigoroso com diferentes juízes fundacionais da AWS.",
    "## Evaluator design notes": "## Notas de Engenharia de Avaliadores (System Design)",
    "### Custom evaluator levels and placeholders": "### Estruturação Semântica de Placeholders",
    "Each evaluator level requires specific **placeholders** in the instructions. These placeholders are filled in automatically with data from agent traces:": "Cada instrução no motor LLM exige o mapeamento em chaves AWS predefinidas na string (Placeholders), populadas com as variáveis de execução de nuvem nativa.",
    "| Level | Required placeholders (at least one) | Best for |": "| Nível Hierárquico | Placeholders Essenciais na Configuração | Melhor uso na AWS |",
    "| **SESSION** | `{context}`, `{available_tools}`, `{actual_tool_trajectory}`, `{expected_tool_trajectory}`, `{assertions}` | Full conversation quality |": "| **Sessão (SESSION)** | `{context}`, `{available_tools}`, `{actual_tool_trajectory}`, `{expected_tool_trajectory}`, `{assertions}` | Score Macro e de UX. |",
    "| **TRACE** | `{context}`, `{assistant_turn}`, `{expected_response}` | Individual turn quality |": "| **Restrito (TRACE)** | `{context}`, `{assistant_turn}`, `{expected_response}` | Depuração de micro inferências. |",
    "| **TOOL_CALL** | *(built-in only)* | Tool selection accuracy |": "| **Específico de Ferramenta (TOOL_CALL)** | Padrões de código AWS *(somente nas built-ins)*. | Qualidade no trigger da chamada da REST API. |",
    "Placeholders with `expected_` require **reference inputs** (ground truth) and can only be used for **on-demand** evaluation. For **online** evaluation (continuous monitoring), use built-in evaluators or custom evaluators that only reference actual data.": "Cláusulas estritas com rótulos `expected_` necessitam fortemente de dados validados (arquivos Golden Dataset ou matriz de resposta esperada) via input da `API`. Elas só rodam em modelo lote/on-demand.",
    "### Rating scale": "### Rating Scale e Regras de Configuração JSON",
    "Each evaluator defines a **numerical rating scale** with labels and definitions. The LLM judge outputs a score with justification. The `evaluatorConfig` uses the `llmAsAJudge` structure:": "A topologia de configuração exige que `ratingScale` tenha suporte completo de range numérico. A classe se acopla em `evaluatorConfig`:",
    "### Online vs on-demand evaluation": "### Online vs Processamento em Massa On-Demand",
    "| Mode | How it works | When to use |": "| Interface Executável | Como opera na Infraestrutura | Cenário e Aplicabilidade Técnica |",
    "| **Online** | Continuously samples live traffic from CloudWatch Logs | Production monitoring |": "| **CloudWatch Sink (Online)** | Filtra amostras (Samples) do fluxo contínuo de inferência log-stream nativo da AWS. | Uso Corporativo de painéis operacionais na Produção. |",
    "| **On-demand** | Evaluates specific traces/sessions by ID | Testing, investigation, debugging |": "| **REST Endpoint (On-demand)** | Avalia lotes de matriz JSON extraídos por SDK (via ID). | Ideal para debug local, pipelines CI/CD em regressões e relatórios executivos atrasados. |",
    "Online evaluations use the `create_online_evaluation_config` API (control plane) and require an IAM execution role with CloudWatch Logs read permissions and Bedrock model invocation permissions.": "Rotinas baseadas na nuvem ativa (online) obrigatoriamente se utilizam do IAM Role de execução restrita para o permissionamento da invocação e acesso as métricas CloudWatch.",
    "## What's next": "## O último passo da Arquitetura Produtiva",
    "All **9 AgentCore services** are now active for Aria:": "Todos os **9 microsserviços do ecosistema AgentCore** operam juntos nativamente.",
    "1. **Runtime** -- Hosts the Strands agent": "1. O ambiente gerenciado (**Runtime**) isolando o contêiner Strands Python.",
    "2. **Code Interpreter** -- Python execution sandbox": "2. Ambientes de teste herméticos via **Interpretador de Código (Code Interpreter)**.",
    "3. **Browser Tool** -- Web browsing capability": "3. Componentes remotos como as sessões do Navegador via **Browser Tool**.",
    "4. **Memory** -- Short-term and long-term memory (preferences, facts, summaries)": "4. Subsistema unificado LTM & STM em nuvem AWS DynamoDB por intermédio da **Memória (AgentCore Memory)**.",
    "5. **Gateway** -- MCP protocol bridge to the Task API": "5. Proxy reverso do protocolo standard MCP e Roteamento de Ferramentas providos pela infraestrutura restrita do **Gateway (AgentCore Gateway)**.",
    "6. **Identity** -- CUSTOM_JWT authentication via Cognito": "6. Governança total da topologia JWT RSA originada em `Cognito` via sub-sistema nativo de Auth (Identidade/Identity).",
    "7. **Policy** -- Cedar policy enforcement at the Gateway": "7. Auditoria estrita em tráfego leste-oeste via **Policy Engine (AgentCore Policy)** e a especificação Cedar.",
    "8. **Observability** -- Automatic OTel tracing to CloudWatch": "8. Agregados em grafos de traces OpenTelemetry enviados ativamente ao painel do **CloudWatch Observability**.",
    "9. **Evaluations** -- LLM-as-judge quality monitoring": "9. Inferência de qualidade automática orientada à base sólida provida pelo serviço **Avaliações (AgentCore Evaluations)**.",
    "In **Module 8**, we review the full architecture, verify all services, and run integration tests across every capability.": "Neste ponto focal do Módulo 8, faremos os testes automatizados de Integração Sistêmica fim a fim.",

    # MODULE 08
    "# Module 8: Full Deployment -- The Complete Picture": "# Módulo 8: Deploy Integral e Testes de Integração de Arquitetura",
    "**Congratulations!** You have built **Aria**, a production AI assistant powered by all 9 Amazon Bedrock AgentCore services. This module reviews the full architecture, verifies every service is active, runs integration tests, and provides cleanup instructions.": "**Concluído!** A implementação corporativa e governada da **Aria** executando nativamente em toda infraestrutura da AWS AgentCore foi completada. O laboratório 8 finaliza com testes e roteiros seguros para os testes da arquitetura, antes do desmonte infraestrutural de sua Cloud.",
    "## Architecture review": "## Arquitetura Sistêmica Integral (Review Lógico)",
    "Here is the complete architecture you have built across Modules 2-8:": "Esta topologia modela integralmente o sistema distribuído provido pela AWS (Módulo 2 ao Módulo 8).",
    "### The 9 AgentCore services + frontend": "### O Cluster do AgentCore AWS Interconectado com o Endpoint React Web",
    "| # | Service | Module | Role |": "| Ordem Sequencial AWS | Microsserviço Subjacente | Implementação | Propósito de Engenharia |",
    "| 1 | **Runtime** | 02 | Hosts the Strands agent, manages invocations and lifecycle |": "| 1 | **Runtime** | Mod 02 | Contêiner Seguro gerenciado (Strands Agent/Python) acoplado a ciclo de vida auto-scale |",
    "| 2 | **Code Interpreter** | 03 | Sandboxed Python execution for calculations and data analysis |": "| 2 | **Code Interpreter** | Mod 03 | Sandbox Python Isolado - Roda algoritmos, matemática, parseio via bibliotecas nativas |",
    "| 3 | **Browser Tool** | 03 | Web browsing for current information retrieval |": "| 3 | **Browser Tool** | Mod 03 | Navegação remota em Headless Chrome encapsulado via Bedrock Tool. |",
    "| 4 | **Memory** | 04 | Short-term (session events) and long-term (preferences, facts, summaries) memory |": "| 4 | **Memory** | Mod 04 | Ingestão autônoma em Backend (DynamoDB wrapper). LTM & STM em sincronia restrita ao ID. |",
    "| 5 | **Gateway** | 05 | MCP protocol bridge connecting the agent to external APIs |": "| 5 | **Gateway** | Mod 05 | Acoplamento de Target API via interface MCP gerenciada nativa |",
    "| 6 | **Identity** | 05 | CUSTOM_JWT authentication forwarding user identity through the stack |": "| 6 | **Identity** | Mod 05 | Validador rigoroso do Bearer Token e propulsor da infraestrutura CUSTOM_JWT em nuvem. |",
    "| 7 | **Policy** | 06 | Cedar policy enforcement — deterministic guardrails at the Gateway |": "| 7 | **Policy** | Mod 06 | Motor Determinístico base (Cedar) - Interrompe acesso em milissegundos bloqueando a Payload de rede |",
    "| 8 | **Observability** | 07 | OpenTelemetry tracing to CloudWatch (ADOT SDK + explicit enablement) |": "| 8 | **Observability** | Mod 07 | Exportador central ADOT - Processo daemon acoplado nativamente na nuvem emitindo AWS X-Ray. |",
    "| 9 | **Evaluations** | 07 | LLM-as-judge quality monitoring with custom rubrics |": "| 9 | **Evaluations** | Mod 07 | Juízes baseados em IA - Score numérico dinâmico extraído on-the-fly sobre OTel Dumps. |",
    "| -- | **Frontend** | 08 | Web app with streaming chat, sessions, and Cognito auth |": "| -- | **Frontend SPA** | Mod 08 | PWA/WebApp integrando SSE HTTP e OAuth Flow do Cognito. |",
    "## Verify all services": "## Validação Forense das APIs (Boto3 SDK)",
    "Let's confirm that every AgentCore resource is active and properly configured using raw boto3 calls.": "Teste lógico de Integridade e Dependências via chamadas não-estruturadas Boto3 REST. Nenhum nó pode retornar Null.",
    "## Deploy the frontend web application": "## Build & Deploy (SPA Frontend AWS)",
    "Now let's deploy a web application so you can interact with Aria through a browser.": "Processo de liberação ao usuário final: Acoplar o Backend completo num Web Client seguro e assíncrono.",
    "The frontend infrastructure (API Gateway, Lambda functions, S3 bucket, CloudFront distribution, DynamoDB sessions table) was **pre-provisioned** by the workshop CloudFormation template. The deploy script wires it all up with the AgentCore resources you created in Modules 2-7:": "Os blocos originais (API Gateway regional, Lambdas em python, CloudFront DNS mapping, S3 Block Store e Banco Operacional DynamoDB) nasceram todos provisionados pelo script basilar de pre-requisitos via CloudFormation. A etapa presente injeta todo seu trabalho do `AgentCore` nessa arquitetura estática inicial:",
    "1. **Configures the Runtime for OAuth** — enables direct HTTPS calls with a Cognito JWT": "1. **Concessão OAuth no Runtime** — Habilita comunicação Server-Sent Events diretamente de conexões com claims JWT Cognito corretos.",
    "2. **Adds the POST /chat endpoint** to the pre-provisioned API Gateway, pointing to the Runtime": "2. **Injeta roteamento no AWS API Gateway** — Aponta a Rota API Rest `/chat` ao Runtime.",
    "3. **Updates the history Lambda** with the Memory ID for conversation history retrieval": "3. **Persiste o LTM via Lambda** — O script de memória atualiza a base da lambda do histórico com ID local.",
    "4. **Uploads frontend files** to S3 with a generated `config.js` containing all endpoints": "4. **Upload S3 de Build Produtivo Web** — Script escreve config.js em tempo real com ARNs globais e dispara PUT pro Bucket WebS3.",
    "5. **Invalidates the CloudFront cache** so the new files are served immediately": "5. **Trigger de Cache Invalidation** — Expurga os arquivos defasados no cluster CDN CloudFront globalmente e injeta na beira os arquivos buildados.",
    "## Access the web application": "## Ponto de Conexão na Produção Final",
    "The frontend is now live. Open the CloudFront URL below in your browser and log in with the workshop credentials:": "Infraestutura totalmente operacional e acessível via Amazon CloudFront. Faça autenticação:",
    "- **Username:** `workshop@example.com`": "- **Usuário ID:** `workshop@example.com`",
    "- **Password:** `WorkshopPass123!`": "- **Master Key:** `WorkshopPass123!`",
    "Try these conversations to exercise all of Aria's capabilities:": "A validação (End to End Testing E2E) deverá explorar todas as fronteiras de integração dos FMs:",
    "1. **\"Remember that my favorite programming language is Python\"** -- tests Memory": "1. **Persistência Neural:** \"Salve nas preferências e lembre-se, minha linguagem primária é o python\" (Testa Memory Node LTM).",
    "2. **\"Calculate the first 20 Fibonacci numbers\"** -- tests Code Interpreter": "2. **Carga em Sandbox Restrito:** \"Construa o fibonacci de 20 e me dê os números resultantes numérico.\" (Testa o Code Interpreter Serverless CPU).",
    "3. **\"Create a task: Review the AgentCore documentation\"** -- tests Gateway + Policy": "3. **Integração Target-Role IAM:** \"Aloque a tarefa ler docs na cloud AWS\". (Chama MCP > Intercepta no Cedar Gateway > Bate na Lambda > Grava DynamoDB).",
    "4. **\"What's the latest news about AWS re:Invent?\"** -- tests Browser Tool": "4. **Conexão Real-Time Internet:** \"O que tem de novidade no AWS Re:Invent 2024?\" (Roteamento nativo usando Chrome).",
    "5. **Start a new session and ask \"What's my favorite programming language?\"** -- tests cross-session Memory": "5. **Session Dropping:** Renovar Chat inteiro, apagar tela. Inquerir: \"Ok, qual é de fato a melhor linguagem de cloud para mim?\" (Valida cross-session LTM lookup heurístico).",
    "## What you have learned": "## Relatório Técnico Conclusivo e Recapitulação",
    "Across this workshop, you built a production AI assistant from scratch using Amazon Bedrock AgentCore:": "A engenharia foi implementada inteiramente no stack modular nativo de Cloud do AWS AgentCore:",
    "| Module | What you did | Key takeaway |": "| Labs Técnicos Operacionais | Implementação Arquitetural | Entregável Real de Produção |",
    "| **00** | Set up prerequisites | CloudFormation provisions IAM roles, S3 bucket, Cognito, Task API |": "| **00** | Automação e Provisionamento Basilar | Infraestrutura global como Código (CloudFormation e SAM IAM). |",
    "| **01** | Explored the CLI | `agentcore` CLI for local development and testing |": "| **01** | Linha de Comando (CLI AWS AgentCore) | Ferramentas essenciais para o loop interno (SDLC Local). |",
    "| **02** | Created Runtime | Deployed a Strands agent to AgentCore Runtime |": "| **02** | Injeção Lógica no Runtime Python | Contêiner Seguro com SDK AWS. Streaming por default. |",
    "| **03** | Added Tools | Code Interpreter and Browser Tool -- zero infrastructure |": "| **03** | Ferramentas de Nuvem AWS Zero-Config | Injeção robusta sem a dor da governança ou instalação local. |",
    "| **04** | Added Memory | Session summaries, user preferences, and semantic facts |": "| **04** | Memória Vectorial Heurística e Transacional | Múltiplas instâncias gerando STM & LTM orgânicos e isolados. |",
    "| **05** | Added Gateway + Identity | MCP bridge to REST APIs with JWT authentication |": "| **05** | Gateway Inteligente em IAM Cognito | Arquitetura segura interligando API legado (via MCP). |",
    "| **06** | Added Cedar Policies | Deterministic guardrails that enforce business rules |": "| **06** | Escudo de Barreira Operacional Cedar | Proteções imutáveis que previnem ações destrutivas ou fraudes. |",
    "| **07** | Added Observability + Evaluations | Auto-tracing and LLM-as-judge quality monitoring |": "| **07** | Matriz Completa CloudWatch (Log + Traces) e Auditing Automático | Soluções reais escalonáveis corporativas na Bedrock OTel. |",
    "| **08** | Deployed the web app | Full frontend with streaming chat, sessions, and Cognito auth |": "| **08** | Go-live (Infraestrutura de Interface e Rede) | CloudFront edge servindo a camada final segura para usuário via SSE. |",
    "The key architectural insight: each AgentCore service handles one concern, and they compose together cleanly. The agent code itself (Aria) stays simple -- it is a Strands agent with a system prompt and tools. All the production infrastructure (auth, policies, tracing, evaluation) lives in the AgentCore platform layer.": "A arquitetura adota profundamente o paradigma de Single Responsibility (responsabilidade única de microsserviço), o que compõe malhas elásticas perfeitas na nuvem. O código fonte no backend Python segue enxuto: Ele se preocupa com IA e não com a infraestrutura e governança AWS. Essas rotinas sensíveis habitam inteiramente na camada de infra AgentCore Platform.",
    "The frontend connects to AgentCore Runtime through an API Gateway streaming proxy. The user's Cognito JWT flows through the entire stack: API Gateway validates it, the Runtime receives it, and the Gateway forwards it to downstream tools. Cedar policies enforce business rules at the Gateway layer without any changes to the agent code.": "A infra Web acessa via streaming proxy (Gateway AWS Serverless). A chave-pilar na engenharia está no JWT gerado no login, ele dita os limites de todo acesso interno em Runtime-Downstream. E, novamente, sem que o código altere uma vírgula de arquitetura lógica.",
    "## Cleanup": "## Limpeza da Infraestrutura Cloud AWS",
    "When you are done with the workshop, run the cleanup cell below to delete all AgentCore resources (Runtime, Memory, Gateway, Policy Engine).": "Terminou? Faça o desmanche (Tear down) preventivo via deleção em CLI. O código a seguir encerra recursos do AgentCore com sucesso e sem rastros tarifados.",
    "> **Workshop Studio note:** If you are running this in an AWS Workshop Studio environment, the CloudFormation stack (IAM roles, Cognito, Task API, frontend infrastructure) will be **cleaned up automatically** when your workshop session expires. You only need to delete the AgentCore resources created during the workshop.": "> **Atenção (Workshop AWS Integrado):** Em ambientes nativos de Studio o tempo expira automaticamente deletando infraestrutura associada de backend pesado (RDS, S3, lambdas base, cognito etc). Você só precisará executar exclusão nas APIs recém injetadas na nuvem. A AWS varrerá o resto no término da janela operacional.",
    "For self-hosted environments, you will also need to delete the CloudFormation stacks (`cfn-template` and `code-editor`) manually from the CloudFormation console.": "Sendo seu cluster próprio self-hosted da empresa, os recursos persistentes legados nas `stacks` (cfn e infra visual de nuvem) exigirão o Excluir no Painel de Controle oficial.",
    "## Next steps": "## Passos Futuros",
    "Now that you have built a complete AgentCore application, here are some directions to explore:": "Com esta especialização e implantação complexa, experimente ampliar os limites arquiteturais:",
    "- **Add more Gateway targets**: Connect additional APIs (calendar, email, CRM) as MCP targets": "- **Extensão Severa em Gateways Targets**: Ampliar a IA integrando Sistemas CRM Corporativos (Salesforce), Mensageiros REST e API's ERP via MCP standard AWS.",
    "- **Refine Cedar policies**: Add per-user or per-role policies using JWT claims as Cedar principals": "- **Escalar Segurança em Políticas (Policy/Cedar)**: Limitar acessos na empresa inteira através de Role Based Claims extraídas nativamente do JWT AWS Cognito (Isolando a operação por Time - Admins vs Users).",
    "- **Custom evaluators**: Create domain-specific evaluators for your use case (compliance, tone, safety)": "- **Monitoramento IA Absoluto (Custom Evaluators)**: Escalar Avaliadores com base de referências que garantam que sua corporação e Compliance AWS são estritamente observados pelo Agente Aria (Auditorias rigorosas do Output em tom de Resposta).",
    "- **Multi-agent architectures**: Use AgentCore Gateway to connect multiple agents together": "- **Nós Distribuídos (Multi-Agent Swarm)**: Ativar infraestrutura na qual diversos perfis autônomos acessam o AgentCore Gateway como elos intercomunicáveis (Modelagem Complexa Multi-IA).",
    "- **Production deployment**: Set up CI/CD pipelines for agent code updates using `deploy_agent.deploy()`": "- **Maturidade MLOps/DevOps (Prod)**: Automatizar toda essa esteira contínua nativa através do AWS CodePipeline integrado ao trigger de `deploy_agent.deploy()`. O ambiente AWS lida maravilhosamente bem com deploy nativo contínuo via esteira CI/CD.",
    "**Congratulations!** You have completed the Amazon Bedrock AgentCore workshop. Aria is a fully production-ready AI assistant with a web frontend, powered by all 9 AgentCore services, authenticated with Cognito, and protected by Cedar policies.": "**Parabéns pela Engenharia AWS!** Ao finalizar toda a implementação, a Aria é formalmente uma aplicação servless em modo de Produção Contínua com base nativa nos nove principais serviços do ecossistema Amazon AgentCore.",

    # MODULE 99
    "# Admin Tools": "# Console de Ferramentas de Limpeza Sistêmica AWS",
    "Emergency cleanup cells for deleting AgentCore resources created by workshop notebooks.": "Comandos de expurgo forçado de emergência na rede em que o AgentCore executou provisionamento.",
    "Run individual cells to delete specific resources, or run **Delete All** at the bottom to nuke everything.": "Execute o snippet Python ou Boto correspondente no alvo isolado AWS, ou use o modo **Tear Down / Nuke All** para deleção maciça em árvore.",
    "> **Warning:** These operations are destructive and cannot be undone. You will need to re-run the relevant module notebooks to recreate deleted resources.": "> **ATENÇÃO TÉCNICA E CUSTOS (Warning):** Estas rotinas REST chamam exclusão absoluta e são irreversíveis. Em caso de infraestrutura legada e perdas você precisará iterar os módulos 2 ao 7 novamente rodando os arquivos Python da pasta do laboratório de engenharia na íntegra.",
    "## 1. Delete Agent Runtime": "## Etapa 1. Apagar e Deletar Contêiner Runtime AWS",
    "Deletes the `aria_agent` runtime. This removes the deployed agent and all its sessions.": "Ação sobre a base `aria_agent`. O Agente inteiro, seu pipeline, as microVM isoladas por id ativas e tudo do Strands será desconectado e eliminado do cluster na nuvem.",
    "## 2. Delete Memory": "## Etapa 2. Aniquilar Memory Database AWS",
    "Deletes the `AriaMemory` resource and all stored conversation data.": "Comando de desmanche AWS no componente de Infra `AriaMemory` com purga completa LTM / STM corporativa atrelada (DynamoDB wrapper).",
    "## 3. Delete Gateway": "## Etapa 3. Encerrar Roteador do AWS Gateway MCP",
    "Deletes the `aria-gateway` and all its targets (e.g., the Task API target).": "Anular instâncias associadas às tabelas e roteamento restrito da VPC interna que ligavam a API ao Agent. Os targets desaparecerão.",
    "## 4. Delete Policy Engine": "## Etapa 4. Interromper Mecanismo Restrito Policy Engine e Regras Cedar",
    "Deletes the `aria-policy-engine` and all its Cedar policies.": "Acionar cancelamento absoluto do módulo `aria-policy-engine`, com limpeza simultânea remota das cláusulas rígidas Cedar em IAM.",
    "## 5. Delete All": "## Etapa de Nuvem 5. Tear Down Integral (Apagar a Infra completa AWS)",
    "Runs all cleanup steps above in the correct order (policy engine first, then gateway, memory, and finally runtime).": "Sequência autônoma orquestrada que elimina hierarquicamente respeitando proteções estritas (Policy > Gateway > Memory > e, finalmente o Contêiner Runtime global Python) mitigando erro interno na AWS Cloud."
}

def run():
    for f in glob.glob('*/notebook.ipynb', recursive=True):
        if '07-observability' in f or '08-full-deployment' in f or '99-admin' in f:
            with open(f, 'r', encoding='utf-8') as file:
                nb_data = json.load(file)
            
            modified = False
            for cell in nb_data.get('cells', []):
                if cell.get('cell_type') == 'markdown':
                    new_source = []
                    for line in cell.get('source', []):
                        new_line = line
                        for en_text, pt_text in mod07_99_translations.items():
                            if en_text in new_line:
                                new_line = new_line.replace(en_text, pt_text)
                                modified = True
                        new_source.append(new_line)
                    cell['source'] = new_source
                    
            if modified:
                with open(f, 'w', encoding='utf-8') as file:
                    json.dump(nb_data, file, indent=2, ensure_ascii=False)
                print(f"Translated {f}")

if __name__ == '__main__':
    run()
