import json

mod01_03_translations = {
    # MODULE 1
    "# Module 1: Introduction to Amazon Bedrock AgentCore": "# Módulo 1: Introdução ao Amazon Bedrock AgentCore",
    "## What is Amazon Bedrock AgentCore?": "## O que é o Amazon Bedrock AgentCore?",
    "**Amazon Bedrock AgentCore** is a suite of managed services purpose-built for deploying, securing, and operating AI agents in production. It removes the undifferentiated heavy lifting of agent infrastructure so you can focus on building agent logic.": "**Amazon Bedrock AgentCore** é um conjunto de serviços gerenciados feitos sob medida para colocar agentes de IA em produção de forma segura. Ele cuida de toda a infraestrutura chata e pesada para que você possa focar apenas em construir a lógica do seu agente.",
    "### Why AgentCore matters": "### Por que o AgentCore é importante",
    "Building a prototype AI agent is easy. Getting one into production is hard. You need to solve for:": "Criar um protótipo de IA é fácil. O difícil é colocar em produção. Você precisa resolver problemas como:",
    "- **Hosting & scaling** -- Where does the agent run? How does it scale to thousands of users?": "- **Hospedagem & Escala** -- Onde o agente roda? Como ele aguenta milhares de usuários ao mesmo tempo?",
    "- **Tool access** -- How does the agent execute code, browse the web, or call APIs safely?": "- **Acesso a Ferramentas** -- Como o agente roda código, acessa a web ou chama APIs com segurança?",
    "- **Memory** -- How does the agent remember past conversations and user preferences?": "- **Memória** -- Como o agente lembra do que já foi conversado e das preferências do usuário?",
    "- **Authentication** -- How do you know who is talking to the agent?": "- **Autenticação** -- Como você sabe quem está falando com o agente?",
    "- **Authorization** -- What is each user allowed to do?": "- **Autorização** -- O que cada usuário tem permissão para fazer?",
    "- **Observability** -- How do you debug failures and monitor quality?": "- **Observabilidade** -- Como você descobre erros e monitora a qualidade das respostas?",
    "- **Evaluation** -- How do you know the agent is actually good?": "- **Avaliação** -- Como você sabe que o agente é realmente bom?",
    "AgentCore provides a managed answer for every one of these challenges.": "O AgentCore resolve tudo isso para você de forma totalmente gerenciada.",
    "## The 9 AgentCore Services": "## Os 9 Serviços do AgentCore",
    "AgentCore is composed of 9 services that work together to form a complete agent platform:": "O AgentCore é formado por 9 serviços que trabalham juntos para criar uma plataforma completa:",
    "### Compute & Tools": "### Computação e Ferramentas",
    "| Service | What it does |": "| Serviço | O que faz |",
    "|---------|-------------|": "|---------|-------------|",
    "| **Runtime** | Hosts and scales your agent in a secure, serverless environment. Each session gets its own dedicated microVM with isolated CPU, memory, and filesystem -- so your agent code only handles one session at a time and conversation history is preserved automatically. |": "| **Runtime** | Roda e escala o seu agente num ambiente seguro. Cada conversa (sessão) ganha sua própria microVM isolada -- então seu código só precisa se preocupar com uma pessoa por vez, e o histórico é mantido automaticamente. |",
    "| **Code Interpreter** | Gives your agent a sandboxed Python execution environment. The agent can write and run code, generate charts, and process files -- all in a secure sandbox. |": "| **Interpretador de Código** | Dá ao seu agente um ambiente seguro para rodar Python. Ele pode escrever código, gerar gráficos e ler arquivos, tudo sem risco para o sistema principal. |",
    "| **Browser Tool** | Gives your agent the ability to browse the web. It can navigate pages, extract content, and interact with web applications. |": "| **Navegador Web** | Permite que seu agente acesse a internet. Ele pode abrir páginas, ler o conteúdo e interagir com sites. |",
    "### Memory & State": "### Memória e Estado",
    "| **Memory** | Provides persistent, cross-session memory. The agent remembers past conversations, user preferences, and extracted facts without you managing a database. |": "| **Memory** | Dá memória de longo prazo para o agente. Ele lembra do que você falou ontem ou semana passada, sem você precisar configurar um banco de dados. |",
    "### Security & Access": "### Segurança e Acesso",
    "| **Gateway** | A managed MCP gateway that converts your APIs, Lambda functions, and existing services into MCP-compatible tools -- and connects to pre-existing MCP servers -- making them available to AI agents through a secure endpoint. |": "| **Gateway** | Um gateway que pega as suas APIs ou funções Lambda e transforma tudo em ferramentas fáceis pro seu agente usar de forma segura. |",
    "| **Identity** | Integrates with identity providers (like Amazon Cognito) to authenticate end users before they reach your agent. |": "| **Identidade** | Se conecta com sistemas de login (como o Amazon Cognito) para ter certeza de quem é o usuário antes dele falar com o agente. |",
    "| **Policy** | Enforces fine-grained authorization using [Cedar](https://www.cedarpolicy.com/) policies. Control what each user or group can do -- down to individual tool calls. |": "| **Política** | Aplica regras de segurança super precisas usando políticas Cedar. Você controla o que cada um pode fazer, bloqueando até mesmo o uso de uma ferramenta específica. |",
    "### Quality & Operations": "### Qualidade e Operações",
    "| **Observability** | Emits structured traces, metrics, and logs for every agent invocation. Integrates with Amazon CloudWatch for dashboards and alarms. |": "| **Observabilidade** | Gera logs, métricas e rastros de tudo que o agente faz, integrando direto com o Amazon CloudWatch para você montar painéis. |",
    "| **Evaluations** | Runs automated quality assessments against your agent using configurable test suites. Validates that your agent meets accuracy, safety, and latency targets. |": "| **Avaliações** | Roda testes automáticos pra ver se o seu agente tá mandando bem nas respostas, se é seguro e se responde rápido. |",
    "### How they fit together": "### Como tudo se encaixa",
    "## The Strands Agents SDK": "## O SDK do Strands Agents",
    "AgentCore is **framework-agnostic** -- you can deploy agents built with any framework. However, in this workshop we use the **[Strands Agents SDK](https://strandsagents.com)**, an open-source Python SDK from AWS that is designed to work seamlessly with AgentCore.": "O AgentCore funciona com **qualquer framework**. Mas neste curso, vamos usar o **Strands Agents SDK**, um SDK Python de código aberto da AWS que foi feito sob medida para casar perfeitamente com o AgentCore.",
    "Strands provides:": "O Strands te dá:",
    "- A simple `Agent` class with built-in tool calling and multi-turn conversation": "- Uma classe `Agent` simples que já sabe como usar ferramentas e manter conversas longas",
    "- Native integration with AgentCore services (Memory, Code Interpreter, Browser Tool)": "- Integração nativa com os serviços do AgentCore (Memória, Código e Navegador)",
    "- Automatic trace emission for AgentCore Observability": "- Geração automática de logs para a Observabilidade do AgentCore",
    "- A lightweight, composable architecture": "- Uma arquitetura leve e fácil de montar",
    "## The AgentCore CLI (FYI)": "## A Linha de Comando do AgentCore (Só pra você saber)",
    "AgentCore provides a CLI for creating, developing, and deploying agents. The CLI is an npm package (`@aws/agentcore`) that requires **Node.js 20.x or later** and **uv** (for Python agents).": "O AgentCore tem um CLI pra facilitar a vida na hora de criar e fazer deploy. É um pacote npm (`@aws/agentcore`).",
    "> **Note:** We won't use the CLI in this workshop -- we'll work directly with boto3 so you can see the underlying API calls. But the CLI is useful to know about for when you want to move fast outside of a workshop setting.": "> **Nota:** Não vamos usar o CLI nesse curso -- vamos usar o `boto3` direto no código pra você entender como a API funciona por debaixo dos panos. Mas é bom saber que o CLI existe para quando você quiser ir mais rápido no dia a dia.",
    "### Installing the CLI": "### Instalando o CLI",
    "On your local machine, you would install it globally via npm:": "Na sua máquina, você instalaria assim:",
    "### CLI help output": "### Comando de ajuda do CLI",
    "Running `agentcore --help` shows the available commands:": "Rodando `agentcore --help` você vê os comandos:",
    "### Key CLI commands": "### Principais comandos do CLI",
    "The CLI organizes around a simple project lifecycle:": "O CLI é focado no ciclo de vida do projeto:",
    "| Command | Description |": "| Comando | Descrição |",
    "| `agentcore create` | Create a new AgentCore project (a wizard guides you through agent setup) |": "| `agentcore create` | Cria um projeto novo (tem um assistente que te ajuda) |",
    "| `agentcore dev` | Start a local development server to test your agent |": "| `agentcore dev` | Sobe um servidor local pra você testar seu agente |",
    "| `agentcore deploy` | Deploy your agent infrastructure to AWS |": "| `agentcore deploy` | Faz o deploy da infra na AWS |",
    "| `agentcore invoke` | Invoke your deployed agent |": "| `agentcore invoke` | Chama o seu agente que já tá na nuvem |",
    "| `agentcore add` | Add resources (agents, memory, identity, evaluators, targets) |": "| `agentcore add` | Adiciona coisas novas (memória, identidade, etc) |",
    "| `agentcore remove` | Remove resources from the project |": "| `agentcore remove` | Remove coisas do projeto |",
    "### Example: Creating a project": "### Exemplo: Criando um projeto",
    "Running `agentcore create` walks you through an interactive wizard:": "Rodar `agentcore create` abre um assistente interativo:",
    "Since this workshop focuses on understanding the underlying APIs, we use boto3 directly in the modules that follow. This gives you full visibility into the API calls, parameters, and response structures that the CLI abstracts away.": "Como a ideia deste curso é você aprender a fundo como a coisa funciona, vamos usar o código puro com boto3. Assim você vê exatamente quais APIs estão sendo chamadas e os parâmetros envolvidos.",
    "## AWS SDKs and the Workshop Approach": "## SDKs da AWS e a Abordagem do Curso",
    "AgentCore resources can be managed through three interfaces:": "Você pode gerenciar o AgentCore de 3 jeitos:",
    "1. **AgentCore CLI** (`agentcore`) — Quick commands for listing, deploying, and testing from the terminal": "1. **AgentCore CLI** (`agentcore`) — Comandos rápidos no terminal.",
    "2. **AWS CDK** — Infrastructure as Code for production deployments": "2. **AWS CDK** — Código para criar a infraestrutura em produção.",
    "3. **AWS SDKs** (e.g., `boto3` for Python) — Programmatic access to all AgentCore APIs": "3. **AWS SDKs** (ex: `boto3` no Python) — Acesso direto via código a todas as APIs.",
    "In this workshop, we primarily use **boto3** because:": "Aqui a gente foca no **boto3** porque:",
    "- You see the exact API calls that create and manage AgentCore resources": "- Você vê exatamente as chamadas de API acontecendo.",
    "- You understand the parameters, configurations, and response structures": "- Você entende as configurações e como a AWS responde.",
    "- The same calls work in your production code": "- Esse mesmo código vai rodar na sua produção de verdade.",
    "### Helper functions": "### Funções auxiliares (Helpers)",
    "We provide a `shared/` utilities directory with helper functions for:": "Nós deixamos uma pasta `shared/` com algumas ajudas:",
    "- **`ensure_ready(module)`** — Smart catch-up script. Checks what exists, creates what's missing. Run this at the start of any module to guarantee prerequisites are in place (even if you skipped modules or broke something).": "- **`ensure_ready(module)`** — Um script mágico. Ele checa o que você já fez e cria o que tiver faltando. Rode isso no começo de cada módulo para garantir que tudo está certo.",
    "- **`deploy_agent.deploy()`** — Packages agent code into a zip, uploads to S3, and creates/updates the Runtime. We hide this because the packaging boilerplate isn't the learning objective.": "- **`deploy_agent.deploy()`** — Empacota o código em um zip e manda pra AWS. Escondemos esse código chato porque fazer zip não é o objetivo da aula.",
    "- **`progress.show()`** — Visual progress tracker.": "- **`progress.show()`** — Mostra uma barra de progresso visual na tela.",
    "**What we DON'T hide:** The actual AgentCore API calls for creating resources (Memory, Gateway, Policy, Evaluators) and invoking agents. These are the concepts you need to understand, so you'll see them as raw boto3 calls.": "**O que a gente NÃO esconde:** O código de verdade que cria os recursos na AWS (Memória, Gateway, etc). Isso é o que você precisa aprender, então deixamos tudo visível no código Python.",
    "## The Journey Ahead": "## O Caminho Pela Frente",
    "Here is what you will build in each remaining module:": "Dá uma olhada no que vamos construir nos próximos módulos:",
    "### Module 2: Deploy Your First Agent to Runtime": "### Módulo 2: O Primeiro Deploy",
    "Build Aria as a Strands agent and deploy it to AgentCore Runtime. By the end of this module, Aria will be running as a managed, scalable endpoint that you can invoke via the CLI and SDK.": "Vamos colocar a Aria pra rodar lá no AgentCore Runtime. No final do módulo, ela já estará viva e respondendo via código ou terminal.",
    "### Module 3: Add Code Interpreter & Browser Tools": "### Módulo 3: Adicionando Ferramentas (Código e Navegador)",
    "Give Aria superpowers. With Code Interpreter, she can write and execute Python code, generate visualizations, and process files. With Browser Tool, she can navigate the web to research topics and extract information.": "Dando superpoderes para a Aria. Ela vai conseguir programar em Python, gerar gráficos e navegar na internet sozinha para fazer pesquisas.",
    "### Module 4: Add Persistent Memory": "### Módulo 4: Dando Memória",
    "Enable Aria to remember. Using AgentCore Memory, Aria will retain context across sessions -- remembering user preferences, past conversations, and extracted facts.": "Ensinando a Aria a lembrar. Vamos ligar a Memória nela para que ela lembre de você e das conversas passadas mesmo se você fechar e voltar amanhã.",
    "### Module 5: Connect Gateway & Identity": "### Módulo 5: Gateway e Autenticação",
    "Give Aria access to external APIs. AgentCore Gateway is a managed MCP gateway that converts the Task Management REST API into MCP-compatible tools the agent can call. Identity integration with Amazon Cognito ensures every user's JWT flows through the stack so their data stays private.": "Conectando a Aria no mundo externo. O Gateway vai permitir que ela chame sua API de Tarefas. E com o Cognito, garantimos que cada usuário só veja as suas próprias tarefas com segurança.",
    "### Module 6: Enforce Cedar Policies": "### Módulo 6: Regras com Cedar Policy",
    "Add fine-grained authorization. Using Cedar policies through AgentCore Policy, you will control exactly what each user is allowed to do -- down to individual tool calls and data access.": "Adicionando regras de bloqueio. Usando as políticas Cedar, vamos impedir que um usuário acesse ou modifique ferramentas que não tem permissão.",
    "### Module 7: Observability & Evaluations": "### Módulo 7: Observabilidade e Avaliações",
    "Make Aria observable and testable. AgentCore Observability gives you structured traces and metrics for every invocation. Evaluations let you run automated quality checks to ensure Aria meets your standards.": "Colocando tudo sob os holofotes. Vamos ver todos os rastros de uso, criar métricas e colocar outras inteligências artificiais para testar e dar notas automáticas pra Aria.",
    "### Module 8: Full Production Deployment": "### Módulo 8: Tudo em Produção",
    "Bring it all together. Deploy the complete, production-ready version of Aria with all 9 AgentCore services wired up and working in concert.": "Juntando todas as peças. Faremos o deploy da versão final, com direito a site de frontend e a Aria funcionando com os 9 serviços conectados.",
    "## Key Documentation Links": "## Links Importantes",
    "Keep these bookmarked -- you will reference them throughout the workshop:": "Salva esses links, você vai precisar deles:",
    "## Mark Module Complete": "## Marcando o Módulo como Concluído",
    "**Next up: [Module 2 -- Deploy Your First Agent to Runtime](../02-runtime/notebook.ipynb)**": "**Próximo Passo: [Módulo 2 -- Fazendo o Deploy do Primeiro Agente](../02-runtime/notebook.ipynb)**",

    # MODULE 2
    "# Module 2: AgentCore Runtime — Your First Deployed Agent": "# Módulo 2: AgentCore Runtime — O Primeiro Deploy do Agente",
    "In this module, you will deploy Aria as a live agent running on **Amazon Bedrock AgentCore Runtime**.": "Neste módulo, você vai subir a Aria de verdade para rodar no **Amazon Bedrock AgentCore Runtime**.",
    "## What you'll learn": "## O que você vai aprender",
    "- **AgentCore Runtime** — the managed compute layer that hosts, scales, and versions your agents": "- **AgentCore Runtime** — a camada de hospedagem da AWS que roda e escala o seu agente de forma gerenciada",
    "- **How agent code is packaged and deployed** — from a local directory to a running container in the cloud": "- **Como o código é empacotado** — saindo do seu computador até virar um contêiner lá na nuvem",
    "- **The streaming invocation model** — how requests flow from client to agent and back as a stream of events": "- **Como funciona o streaming** — como as perguntas e respostas vão e voltam em tempo real (como se a IA estivesse digitando)",
    "By the end of this module Aria will be live and responding to prompts, though she won't yet have any tools or memory.": "Até o final desta aula, a Aria estará viva e respondendo perguntas (mas ainda sem ferramentas extras nem memória).",
    "## Catch up": "## Atualizando as dependências",
    "The cell below ensures all prerequisites and prior module outputs are in place. If you are jumping into this module directly, it will run any setup needed from earlier modules.": "O código abaixo garante que tudo que precisamos dos módulos anteriores já esteja pronto. Se você pulou algum passo, ele arruma a casa pra você.",
    "## Explore the agent code": "## Conhecendo o código do agente",
    "The agent lives in `agent/main.py`. Before deploying it, let's understand the key pieces.": "O código da Aria mora no arquivo `agent/main.py`. Antes de subir ele, vamos entender os pontos principais.",
    "### BedrockAgentCoreApp": "### A Classe BedrockAgentCoreApp",
    "Every AgentCore agent starts with a **`BedrockAgentCoreApp`** instance. This is the framework's entry point — it handles the HTTP lifecycle, health checks, and communication with the Runtime control plane.": "Todo agente do AgentCore começa instanciando a classe **`BedrockAgentCoreApp`**. É ela que lida com as requisições HTTP, verifica se está tudo funcionando e fala com os controles do Runtime.",
    "### The `@app.entrypoint` decorator": "### O decorador `@app.entrypoint`",
    "You register your agent logic with `@app.entrypoint`. The decorated function receives:": "É com esse decorador que a gente avisa onde o código principal começa. Ele recebe duas coisas:",
    "- **`payload`** — the incoming request (contains the user message, session info, etc.)": "- **`payload`** — a requisição chegando (com a mensagem do usuário, ID da sessão, etc)",
    "- **`context`** — optional metadata about the invocation": "- **`context`** — uns metadados adicionais opcionais",
    "### Async streaming pattern": "### O padrão assíncrono (Streaming)",
    "The entrypoint is an **async generator**. Instead of returning a single response, it **yields events** as the agent thinks and responds. This gives the caller real-time streaming output — the same experience you get in the Bedrock console.": "A função principal é um **gerador assíncrono**. Em vez de devolver tudo de uma vez no final, ela vai soltando a resposta aos pouquinhos (com a palavra `yield`). Isso é o que dá aquele efeito da IA escrevendo o texto na tela em tempo real.",
    "### What does Runtime actually do?": "### O que o Runtime faz, afinal?",
    "When you deploy to AgentCore Runtime, the service:": "Quando você envia seu código pro Runtime, a AWS faz o seguinte:",
    "1. **Packages** your code into a container image": "1. **Empacota** seu código num contêiner docker",
    "2. **Provisions** a dedicated **microVM for each session** — complete isolation of CPU, memory, and filesystem": "2. **Separa** uma pequena máquina virtual (microVM) pra cada sessão — isolando CPU e arquivos totalmente",
    "3. **Scales** automatically based on traffic — including scaling to zero when idle": "3. **Escala** tudo automaticamente, inclusive desligando tudo se ninguém estiver usando",
    "4. **Versions** each deployment so you can roll back if needed": "4. **Cria versões** de cada deploy pra você conseguir voltar atrás se algo quebrar",
    "### Session isolation — the key insight": "### A grande sacada: Isolamento de Sessão",
    "This is one of Runtime's most important features: **each session gets its own microVM**. Your agent code only ever handles one session at a time. This means:": "Essa é a melhor parte: **cada pessoa usando ganha uma microVM só dela**. Seu código só precisa se preocupar em atender uma pessoa por vez. O que isso significa na prática?",
    "- **No multi-session management** — you don't need a session-keyed cache or routing logic. Just create your Agent object and reuse it across invocations.": "- **Sem dor de cabeça gerenciando acessos** — Você não precisa ficar controlando arrays ou caches cheios de sessões. É só criar o Agente e usar.",
    "- **Conversation history is automatic** — the Strands Agent keeps its message list in memory, and since the microVM persists between invocations (up to 8 hours), follow-up messages in the same session see the full conversation history.": "- **O Histórico é automático** — Como a microVM fica ligadinha praquela pessoa (por até 8 horas), o agente sempre lembra das mensagens da sessão.",
    "- **True isolation** — one user's session can never access another user's data. After a session ends, the entire microVM is terminated and memory is sanitized.": "- **Isolamento de verdade** — Um usuário jamais vai cruzar os dados com outro. Fechou a conversa, a máquina é apagada e destruída.",
    "This is why the agent code is so simple — Runtime handles the hard infrastructure problems so your agent code can focus on logic.": "É por isso que o código que vamos escrever é super simples! A AWS cuida da infraestrutura e a gente foca na lógica da IA.",
    "To see the full agent code, open [agent/main.py](agent/main.py) in a new tab.": "Para ver o código completinho, abra o arquivo [agent/main.py](agent/main.py) em outra aba.",
    "The agent's Python dependencies are listed in [agent/requirements.txt](agent/requirements.txt).": "As bibliotecas que ele precisa usar estão listadas no [agent/requirements.txt](agent/requirements.txt).",
    "## Deploy the agent": "## Subindo o Agente pra nuvem (Deploy)",
    "Deployment follows a straightforward pipeline:": "O caminho do deploy é bem direto:",
    "1. **CodeZip packaging** — your agent directory is zipped into a deployment artifact": "1. **Empacotar o Código** — a pasta é compactada num arquivo ZIP",
    "2. **S3 upload** — the artifact is uploaded to the workshop's S3 bucket": "2. **Upload pro S3** — mandamos esse arquivo para o Amazon S3",
    "3. **Runtime creation** — AgentCore pulls the artifact, builds a container, and starts the agent": "3. **Criação do Runtime** — O AgentCore baixa o ZIP, cria o contêiner e sobe ele no ar",
    "4. **READY state** — the agent is live and accepting invocations": "4. **Status READY** — A IA tá no ar e pronta pra receber mensagens",
    "The `deploy_agent` helper handles all of this in a single call.": "Toda essa etapa burocrática foi escondida numa funçãozinha de ajuda chamada `deploy_agent` pra gente ganhar tempo.",
    "> **Other deployment options:** In this workshop we use a Python helper that calls the AgentCore control-plane API directly. You can also deploy agents using the [AgentCore CLI](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/agentcore-get-started-toolkit.html), [AWS CDK](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/agents-tools-runtime.html), or the [AWS Management Console](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/agents-tools-runtime.html). See the [AgentCore Runtime documentation](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/agents-tools-runtime.html) for details on each approach.": "> **E no mundo real?** No dia a dia de trabalho, em vez desse script, você provavelmente usaria o AWS CDK ou o CLI oficial do AgentCore pra subir o agente.",
    "## Enable Tracing": "## Habilitar Logs de Observabilidade (Tracing)",
    "Before invoking the agent, enable **Tracing** for the Runtime so that invocation traces flow to CloudWatch and X-Ray. This populates the AgentCore Observability dashboard you will explore in Module 7.": "Antes de bater papo com a Aria, vamos ativar a função que rastreia tudo o que acontece lá dentro (Tracing), pra gente poder acompanhar depois no CloudWatch.",
    "1. Open the **Amazon Bedrock AgentCore** console and navigate to **Runtimes**": "1. Abra o painel do **Amazon Bedrock AgentCore** no seu navegador e vá em **Runtimes**",
    "2. Select the **aria_agent** runtime": "2. Selecione o runtime **aria_agent**",
    "3. Scroll down to the **Tracing** section and click **Edit**": "3. Desça até a seção de **Tracing** e clique em **Edit** (Editar)",
    "4. Toggle **Enable** on and click **Save**": "4. Marque a chave **Enable** (Habilitar) e clique em **Save** (Salvar)",
    "> **Note:** Tracing must be enabled manually per resource. You will repeat this step for Memory and Gateway in later modules.": "> **Nota:** Essa opção precisa ser ativada manualmente para cada serviço. Vamos fazer isso de novo mais na frente nos outros módulos.",
    "## Invoke the agent": "## Testando o agente (Invocação)",
    "Aria is live. Let's call the deployed agent using the boto3 `bedrock-agentcore` data-plane client. This is the raw API call — no helper functions.": "A Aria tá no ar! Vamos chamar a moça usando a API crua da AWS (`boto3`). Aqui não tem atalho, você vai ver o código oficial de como se comunica com a IA.",
    "You send a JSON payload with a `prompt` key, and the agent streams back a response as **Server-Sent Events (SSE)**. Let's start by looking at the raw response to understand the event format.": "Você manda um JSON com a chave `prompt`, e a AWS te devolve uma resposta em um monte de eventos fracionados (**Server-Sent Events**). Vamos ver a resposta crua e feia primeiro pra entender o que tá acontecendo.",
    "### Understanding the response format": "### Entendendo a resposta crua",
    "The raw output is a stream of **Server-Sent Events (SSE)**. Each line starting with `data: ` contains a JSON object. The agent's text lives inside a nested path:": "A resposta que chega é cheia de marcações, com linhas começando com `data: ` contendo um JSON cada uma. O texto real do que a Aria falou fica escondido aqui dentro:",
    "Let's parse this properly to extract just the agent's text:": "Vamos fazer um pequeno parser (extrator) em Python para limpar toda a sujeira e puxar só o texto puro:",
    "## Chat with Aria interactively": "## Bate-papo pelo Terminal (Interativo)",
    "Now that you understand the invocation model, let's talk to Aria using an interactive CLI chat client. This is a shared tool you will use throughout the workshop for hands-on testing.": "Legal, agora que vimos como funciona por debaixo dos panos, vamos usar um aplicativo simples de chat direto no terminal pra facilitar nossas conversas com a Aria no resto do curso.",
    "Open a **terminal** in your environment:": "Abra um **terminal**:",
    "- In VS Code: **Terminal > New Terminal** (or press `` Ctrl+` ``)": "- No VS Code: **Terminal > Novo Terminal**",
    "- Navigate to this module's directory": "- Entre na pasta deste módulo",
    "Then run:": "E rode:",
    "Try these prompts to explore what Aria can and cannot do:": "Tente brincar com ela fazendo as seguintes perguntas:",
    "1. `Hello! What can you do?`": "1. `Olá! O que você consegue fazer?`",
    "2. `What is the square root of 7,293,461?` — she may hallucinate a number rather than calculate it": "2. `Qual a raiz quadrada de 7.293.461?` — (Ela provavelmente vai inventar um número porque não sabe calcular isso de cabeça)",
    "3. `What is today's weather in Seattle?` — she has no internet access": "3. `Qual é o clima de Seattle hoje?` — (Ela não sabe, pois não tem acesso à internet... ainda)",
    "4. `My name is Alex` — then in the same session: `What's my name?` — she remembers within a session (microVM persistence)": "4. Diga `Meu nome é Alex` — logo depois mande: `Qual é o meu nome?` — (Ela vai lembrar porque a sessão da microVM segura essa memória)",
    "5. Type `new` to start a fresh session, then ask `What's my name?` — she won't remember (no long-term memory yet)": "5. Digite `new` para resetar o chat e pergunte `Qual é meu nome?` — (Ela já esqueceu tudo)",
    "6. Type `quit` to exit": "6. Digite `quit` pra sair",
    "> **Tip:** The chat client uses the same `invoke_agent_runtime` API call you saw above. It reads config from `shared/.config/` automatically. Later in the workshop, when we add authentication, you can run it with `--auth` to use OAuth/JWT.": "> **Dica:** O script do chat usa essa mesmíssima função que acabamos de fazer. Ele pega as configurações automaticamente. Daqui a pouco vamos até incluir uma opção de segurança com `--auth`.",
    "If you tried the prompts above, you will have noticed:": "Se você tentou fazer as perguntas, deve ter notado:",
    "- **No computation** — asking for a square root may produce a hallucinated number rather than a precise calculation.": "- **Ela é péssima de matemática** — Se mandar ela fazer conta difícil, ela apenas 'inventa' a resposta.",
    "- **No live data** — she cannot look up today's weather, stock prices, or news.": "- **Ela está isolada do mundo** — Ela não sabe ler o clima do dia, preços da bolsa ou buscar links.",
    "- **No persistent memory** — within a session she remembers (thanks to the microVM), but across sessions she starts fresh every time.": "- **Amnésia** — Assim que fecha a janela, ela esquece tudo o que você conversou.",
    "## What's next": "## O que vem a seguir",
    "Aria is deployed and responding, but she is limited to what the model already knows. She can't run code, browse the web, or remember past conversations.": "Aria tá viva, mas só tem o cérebro cru treinado de fábrica. Ela não consegue rodar programação, não navega na internet e é esquecida.",
    "In **Module 3: Managed Tools**, we will give Aria two powerful capabilities:": "No **Módulo 3: Ferramentas**, vamos dar dois superpoderes novos pra ela:",
    "- **Code Interpreter** — sandboxed Python execution for calculations, data analysis, and chart generation": "- **Interpretador de Código** — Uma maquininha isolada para ela programar em Python, calcular com perfeição, gerar gráficos e limpar arquivos.",
    "- **Browser Tool** — headless Chrome for live web browsing and content extraction": "- **Navegador Web** — Um navegador invisível (Chrome) para ela abrir sites reais, pesquisar informações e extrair textos da web na hora.",
    "These are managed services provided by AgentCore — no infrastructure for you to maintain.": "Tudo isso fornecido de forma nativa e gerenciada pela AWS AgentCore. Você não vai precisar criar nenhuma infraestrutura pra isso rodar!",
    "**Next up: [Module 3 -- Supercharge Aria with Tools](../03-tools/notebook.ipynb)**": "**Próximo Passo: [Módulo 3 -- Dando Ferramentas para a Aria](../03-tools/notebook.ipynb)**",

    # MODULE 3
    "# Module 3: Managed Tools — Code Interpreter & Browser": "# Módulo 3: Ferramentas — Código e Navegador na Veia",
    "In this module, you will upgrade Aria with two **AgentCore managed tools** that dramatically expand what she can do.": "Neste módulo, você vai dar um upgrade gigantesco na Aria plugando as duas **ferramentas gerenciadas do AgentCore**.",
    "- **AgentCore managed tools** — pre-built, hosted tool services that plug into your agent with a few lines of code": "- **Ferramentas Gerenciadas** — serviços da AWS já prontinhos pra você encaixar no agente com apenas duas linhas de código",
    "- **Browser Tool** — headless Chrome managed by AgentCore for live web browsing and content extraction": "- **Navegador Web** — um navegador Chrome sem tela gerenciado pela AWS pra Aria navegar e extrair informações.",
    "By the end of this module Aria will be able to run Python code and browse the internet — with zero infrastructure for you to manage.": "No final do módulo, a Aria conseguirá rodar código Python perfeito e pesquisar na internet real — e você não vai precisar abrir nenhum servidor pra isso.",
    "## What changed from Module 2 to Module 3?": "## O que mudou de lá pra cá?",
    "The Module 2 agent was a plain Strands agent with no tools. The Module 3 agent adds two managed tool integrations. Here is what's new:": "No módulo anterior, o código do agente era super básico. Agora a gente encaixou as ferramentas nela. Se liga nas novidades:",
    "### Code Interpreter": "### O Interpretador de Código",
    "- Runs Python in a **sandboxed container** managed by AgentCore": "- Ele roda scripts em Python dentro de um **contêiner isolado e seguro**.",
    "- Supports data analysis, mathematical computation, chart/image generation, and file processing": "- Consegue analisar planilhas de dados, calcular fórmulas matemáticas absurdas, gerar imagens/gráficos e lidar com arquivos pesados.",
    "- The sandbox has **no internet access** — it cannot fetch URLs or call APIs": "- A caixa de segurança onde o código roda **não tem acesso à internet** (justamente pra evitar scripts maliciosos de fugirem).",
    "- Ideal for tasks like \"calculate compound interest\" or \"plot a chart of this data\"": "- É perfeito se você pedir: 'calcula o juro composto desse investimento' ou 'desenha um gráfico desses números aqui'.",
    "### Browser Tool": "### O Navegador Web",
    "- **Headless Chrome** managed by AgentCore": "- **Um Chrome invisível** rodando na AWS",
    "- Can navigate to URLs, extract page content, fill forms, and take screenshots": "- Capaz de acessar links, roubar o conteúdo puro da página, preencher dados ou bater fotos das telas.",
    "- Gives your agent real-time access to the web": "- Dá acesso real e imediato ao que tá acontecendo no mundo hoje.",
    "- Ideal for tasks like \"look up today's Bitcoin price\" or \"find the latest blog post\"": "- Perfeito para perguntar: 'qual o preço do Bitcoin hoje às 14h' ou 'lê aquele artigo ali no blog'.",
    "### Both are managed services": "### Serviço Premium Gerenciado",
    "You don't provision instances, manage browser binaries, or handle sandbox security. AgentCore runs the infrastructure and exposes each tool as a simple Python object you pass to your `Agent`.": "Você não vai instalar Chrome no seu Linux, não vai configurar docker pra Python nem se preocupar com segurança. O AgentCore toma conta de toda essa dor de cabeça e te entrega um objetozinho de Python simples pra você ligar no agente.",
    "## Deploy the updated agent": "## Sobe a nova versão! (Deploy)",
    "We'll deploy the updated agent to the same runtime. AgentCore handles the versioned rollout.": "Vamos mandar esse código novo pro mesmo Runtime de antes. O AgentCore substitui a versão atual automaticamente de forma suave e transparente.",
    "## Enable Tracing for Code Interpreter and Browser Tool": "## Habilitar as métricas para as novas ferramentas",
    "Enable **Tracing** on both managed tools so that tool invocations appear in the AgentCore Observability dashboard.": "A gente também precisa habilitar as métricas para o Navegador e o Código, caso a gente queira olhar os logs detalhados depois.",
    "1. Open the **Amazon Bedrock AgentCore** console and navigate to **Built-in tools** > **Code Interpreter**": "1. Abra o painel do **Amazon Bedrock AgentCore** na AWS e navegue até **Ferramentas Inseridas (Built-in tools)** > **Interpretador de Código (Code Interpreter)**",
    "### Browser Tool": "### Navegador Web",
    "1. Navigate to **Built-in tools** > **Browser**": "1. Vai em **Ferramentas Inseridas** > **Navegador (Browser)**",
    "## Set up the invocation client": "## Configurando a chamada do agente",
    "We'll create the boto3 client and a thin local wrapper that keeps the notebook cells clean. The wrapper is defined right here — not hidden in a helper module — so you can see the full `invoke_agent_runtime` call.": "Vamos criar a rotina pra testar de novo. Dessa vez montei um helper local pra não poluir tanto as caixinhas de código. Você pode ver exatamente como as chamadas são feitas no `invoke_agent_runtime`.",
    "## Test Code Interpreter": "## Testando a Mente Matemática",
    "In Module 2, Aria could only answer from her training data. Now she can **write and execute Python code** to give precise, verifiable answers.": "No módulo 2 a Aria chutava números nas respostas. Agora, se ela não souber, ela vai **escrever um programa em Python pra fazer a conta de verdade**.",
    "### Compound interest calculation": "### Cálculo de Juros Compostos",
    "This is a great test because the answer requires real math — not pattern matching.": "Isso é legal porque exige matemática exata, não apenas chutar um palpite.",
    "## Test Browser Tool": "## Testando o Acesso à Internet",
    "The browser tool gives Aria access to live information on the web. Let's try a query that requires real-time data.": "O navegador deixa a Aria checar coisas que estão rolando na internet no mundo real. Vamos mandar uma pergunta do presente.",
    "### Live data lookup": "### Checando informações vivas",
    "## Go deeper": "## Quer se Aprofundar?",
    "To learn more about the managed tools used in this module:": "Pra entender de verdade os detalhes profundos das ferramentas que você acabou de ligar:",
    "- **Code Interpreter:** [AgentCore Code Interpreter documentation](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/code-interpreter-tool.html) — includes file I/O (reading/writing files in the sandbox), supported libraries, and resource limits": "- **Code Interpreter:** [Veja a documentação](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/code-interpreter-tool.html) — Mostra como ler arquivos da máquina segura, os limites de espaço e como adicionar bibliotecas no sandbox.",
    "- **Browser Tool:** [AgentCore Browser documentation](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/browser-tool.html) — includes browser profiles for persistent cookies/sessions, navigation strategies, and content extraction modes": "- **Navegador:** [Documentação aqui](https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/browser-tool.html) — Tem detalhes incríveis sobre como gerenciar cookies de sessão, perfis para preencher formulários de login na web sozinhos e etc.",
    "- **Strands tools integration:** [Strands Agents SDK — Tools](https://github.com/strands-agents/sdk-python) — how managed tools plug into the Strands agent framework": "- **Strands e as ferramentas:** [Repositório Aberto SDK](https://github.com/strands-agents/sdk-python) — mostram como você pode criar ferramentas personalizadas no seu código Python com o framework do Strands.",
    "Aria now has serious capabilities — she can compute, visualize data, and browse the live web. But every conversation still starts from scratch. She has no idea who you are or what you discussed five minutes ago.": "Agora o negócio ficou de verdade! A Aria tem uma super inteligência computacional e enxerga toda a internet. Só tem um problema: ela continua desmemoriada e esquece a conversa 5 minutos depois que você fecha o terminal.",
    "In **Module 4: Memory**, we will give Aria persistent memory so she can:": "No **Módulo 4: Memória**, vamos curar essa amnésia dando uma memória persistente pra ela:",
    "- Remember facts across sessions (\"My name is Alice and I work on the payments team\")": "- Lembrar de você em conversas diferentes ('Oi Aria, lembra que semana passada te falei que eu trabalho na área de RH?')",
    "- Build up context over time": "- Construir familiaridade com a sua forma de trabalhar com o tempo",
    "- Deliver a personalized experience that improves with every interaction": "- Fornecer um tratamento que fica cada vez mais refinado a cada interação de chat.",
    "**Next up: [Module 4 -- Give Aria Persistent Memory](../04-memory/notebook.ipynb)**": "**Próximo Passo: [Módulo 4 -- Dando Memória Pra Valer pra Aria](../04-memory/notebook.ipynb)**"
}

import glob
def run():
    for f in glob.glob('*/notebook.ipynb', recursive=True):
        if '01-intro' in f or '02-runtime' in f or '03-tools' in f or '00-prereq' in f:
            with open(f, 'r', encoding='utf-8') as file:
                nb_data = json.load(file)
            
            modified = False
            for cell in nb_data.get('cells', []):
                if cell.get('cell_type') == 'markdown':
                    new_source = []
                    for line in cell.get('source', []):
                        new_line = line
                        # we replace matching exact substrings
                        for en_text, pt_text in mod01_03_translations.items():
                            if en_text in new_line:
                                new_line = new_line.replace(en_text, pt_text)
                                modified = True
                        new_source.append(new_line)
                    cell['source'] = new_source
                    
            if modified:
                with open(f, 'w', encoding='utf-8') as file:
                    json.dump(nb_data, file, indent=2, ensure_ascii=False)
                print(f"Translated {f}")

if __name__ == '__main__':
    run()
